# Translated by Santi EA2SPS(HAM)
#
#
# SP = Index 10

STR_TABLE_SP = {
    'default_ctext':                "\n-= Hola $destName, =-\n-= Bienvenido a $ownCall ($distance km), =-\n-= al Canal-Terminal $channel <> Puerto $portNr. =-\n-= Está es tu conexión Num. $connNr. =-\n-= $ver - Max-Frame: $parmMaxFrame - Pac-Len: $parmPacLen =-\n\n # Último loggin : $lastConnDate um: $lastConnTime\n\n",
    'default_btext':                '\n73 de $ownCall ...\n',
    'bbs_new_user_reg0':            'Usar esta BBS como su BBS domestica? S/N> ',
    'bbs_new_user_reg_confirm':     'Pulsa <Enter> para confirmar o reentrar al cambio.\r>',
    'bbs_new_user_reg1':            "\rEsta es la primera conexión a este sistema.\rBefore we continue, please answer the questions. THANK YOU!\rTip: You don't have to put yourself through this, there's something called\rthe Internet.\r\rFirst Name:",
    'bbs_new_user_reg2_1':          'Es {}\rstill tu actual  BBS domestica? Y/N> ',
    'bbs_new_user_reg2_2':          'Usar esta BBS como TU BBS domestica? Y/N> ',
    'bbs_new_user_reg3':            'BBS domestica           :',
    'bbs_new_user_reg4':            '\rLo hiciste bien!\r\rDatos de usuario de $destCall:\rNombre: {}\rBBS domestica  : {}\rQTH       : {}\rLocator   : {}\r\r',
    'bbs_new_user_error_hbbs_add':  '\r # Error, el indicativo introducido no es una BBS.\r # {} Type is known as {}.\r # Por favor intentalo de nuevo.\r\r',
    'bbs_new_user_sysopMsg_top':    'Registro nuevo usuario',
    'bbs_new_user_sysopMsg_msg':    '{} acaba de ser conectado a {} por primera vez.\nTime: {}\n',
    'language':                     'Lenguaje',
    'temperature':                  'Temperatura',
    'wx_press':                     'Presión',
    'wx_hum':                       'Humedad',
    'userdb_add_sysop_ent1':        'Añadirninformación?',
    'userdb_add_sysop_ent2':        'Añadir informacion desde el sysop?',
    'userdb_save_hint':             'Info: Datos de usuario {} a sido salvado.',
    'userdb_del_hint1':             'borrar {}?',
    'userdb_del_hint2':             '{} seguro borrar?',
    'userdb_del_hint2_1':           'Borrar {} entradas?',
    'userdb_del_hint2_2':           'Seguro borrar todas  {} entradas?',
    'userdb_newUser':               'Nueva entrada',
    'prewritewin':                  'Ventana de preescritura',
    'consol_log':                   'Salida del Log en la consola',
    'call_vali_warning_1':          'Formato de Indicativo!',
    'call_vali_warning_2':          'Max 6 characteres solo letras mayusculas y  numeros.',
    'del_station_hint':             'Nota: Estacion borrada satisfactotiamente.',
    'del_station_warning_1':        'Estacion borrada',
    'del_station_warning_2':        'Unidad C: ha sido formateada satisfactoriamente.',
    'del_station_hint_1':           'borrar estación',
    'del_station_hint_2':           'Realmente quieres borrar esta estacion? \nAll configuración y textos se perderán!',
    'not_all_station_disco_hint_1': 'Estacion no desconecteda',
    'not_all_station_disco_hint_2': 'No todas las estaciones estan desconectadas!',
    'all_station_get_disco_hint_1': 'Estaciones siendo desconectadas!',
    'all_station_get_disco_hint_2': 'Todas las estaciones siendo desconectadas',
    'close_port':                   'Info: intenta cerrar puerto {}.',
    'port_closed':                  'Info: Puerto {} cerrado satisfactoriamente.',
    'send_kiss_parm':               'Nota: Parámetros Kiss enviados a la TNC en puerto {}..',
    'port_in_use':                  'Error: Puerto {} no puede ser inicializado. El puerto está  en uso.',
    'no_port_typ':                  'Nota: No hay  tipo de puerto seleccionado. puerto {}',
    'port_not_init':                'Error: Puerto {} no puede ser initializado.',
    'port_init':                    'Info: Puerto {} initializado satisfactoriamente.',
    'setting_saved':                'Info: {}-Parametros salvados.',
    'all_port_reinit':              'Info: Los puertos son reinicializados',
    'port_reinit':                  'Info: Puertos {} han sido reinitializados.',
    'all_disco1':                   'Todas las estaciones seran desconectadas!',
    'all_disco2':                   'Todas las estaciones han sido desconectadas',
    'OK':                           'OK',
    'cancel':                       'Cancelar',
    'aborted':                      'Abortado',
    'delete':                       'borrar',
    'next':                         'Siguiente',
    'back':                         'Atras',
    'delete_selected':              'Borrar selección',
    'add':                          'Añadir',
    'activate':                     'Activar',
    'delete_mh_history':            'Borrar Lista MH',
    'delete_dx_history':            'Borrar historial DX-Alarm',
    'delete_tracer_history':        'Borrar historial Trace',
    'delete_conn_history':          'Borrar historial de conexión',
    'del_all':                      'Borrar todo',
    'select_all':                   'Seleccionar todo',
    'go':                           'Ir',
    'close':                        'Cerrar',
    'save':                         'Salvar',
    'forward':                      'Adelante',
    'answer':                       'Rrspuesta',
    'send_file': 'Enviar fichero',
    'file_1': 'Fichero',
    'file_2': 'Fichero:',
    'locator_calc': 'Calculadora Locator',
    'aprs_mon': 'Monitor APRS',
    'protocol': 'Protocolo:',
    'distance': 'Distancia',
    'send_if_free': 'Enviar cuando la banda esté libre por (seg.): ',
    'size': 'Tamaño:',
    'new': 'Nuevo',
    'wait': 'Espere',
    'new_port': 'Nuevo puerto',
    'new_conn': 'Neva Conecxion',
    'disconnect': 'Desconectado',
    'disconnect_all': 'Desconnectar TODOS',
    'disconnect_all_ask': 'Quieres desconectar todas las estaciones?',
    'port_unblock_all': 'Permitir conexiones entrantes (todos los puertos)',
    'port_block_ignore_all': 'Ignorar confecciones entrantes  (todos los puertos)',
    'port_block_reject_all': 'Rechazar  conecxiones entrantes (todos los puertos)',
    'wx_window': 'Estaciones del tiempo',
    'quit': 'Quitar',
    'connections': 'Conecxiones',
    'copy': 'Copiar',
    'past': 'Pegar',
    'cut': 'Cortar',
    'past_f_file': 'Pegar desde Fichero',
    'save_to_file': 'Salvar a Fichero',
    'past_qso_f_file': 'Pegar desde Fichero',
    'save_qso_to_file': 'Salvar QSO a Fichero',
    'save_mon_to_file': 'Salvar Monitor a Fichero',
    'clean_prescription_win': 'Limpiar ventana de prescripción ',
    'clean_just_qso_win': 'Limpiar ventana de  QSO',
    'clean_qso_win': 'Limpiar ventana QSO/Prescripción',
    'clean_all_qso_win': 'Limpiar todas las ventanas de QSO/Prescripción',
    'send_selected': ' Enviar seleccionado',
    'clean_mon_win': 'Limpiar monitor',
    'edit': 'Editar',
    'statistic': 'Estadísticas',
    'history': 'Historia',
    'linkholder': 'titular de enlace',
    'right_level_editor': 'Editor de niveles de derechos',
    'clean_qso': 'borrar QSO',
    'tools': 'Herramientas',
    'station': 'Estacion',
    'stations': 'Estaciones',
    'port': 'Puerto',
    'address': 'Direccion',
    'channel': 'Canal',
    'beacon': 'Baliza',
    'sprech': 'Salida de voz',
    'settings': 'Ajustes',
    'main_page': 'Página principal',
    'password': 'Password',
    'passwords': 'Passwords',
    'syspassword': 'Sys-Password:',
    'trys': 'Intentos falsos:',
    'fillchars': 'Longitud de respuesta:',
    'priv': 'Login',
    'login_cmd': 'Comando de Login:',
    'command': 'Comando',
    'keybind': 'Distribución del teclado',
    'about': 'Acerca de',
    'help': 'Ayuda',
    'number': 'Numero',
    'seconds': 'Segubdo(s)',
    'minutes': 'Minuto(s)',
    'hours': 'Horas',
    'day': 'Día',
    'month': 'Mes',
    'occup': 'Ocupacion en %',
    'call': 'Llamada',
    'name': 'Nombre',
    'fwd_list': 'cola de avance',
    'fwd_path': 'Rutas de avance',
    'start_fwd': 'comienzo FWD',
    'start_auto_fwd': 'Comienzo de AutoFWD',
    'msg_center': 'Centro de Mensajes',
    'text_winPos': 'Posicion del texto (arriba/mitad/abajo)',
    'qso_win_color': 'Color de ventana de QSO',
    'text_color': 'Color de texto',
    'bg_color': 'Color de fondo',
    'backgrund': 'Fondo',
    'mon_color': 'Colores de Monitor',
    'c_text': 'Texto de conexión',
    'q_text': 'Texto Quitar',
    'i_text': 'Texto de Información',
    'li_text': 'Texto de Información larga',
    'news_text': 'Texto de Noticias',
    'comment': 'Comentario',
    'aprs_settings': 'Configuracion de APRS',
    'digi_settings': 'Configuracion DIGI',
    'aprs_server': 'Servidor APRS',
    'conn_2_aprs_server': 'Conectar a servidor APRS',
    'aprs_pn_msg': 'Mensajería APRS',
    'pn_msg': 'Mensajes Privados',
    'msg': 'Mensaje',
    'new_msg': 'Nuevo Mensaje',
    'aprs_digi_settings': 'Digipeater',
    'aprs_tracer_settings': 'Tracer',
    'digi_active': 'Activar APRS Digipeater',
    'digi_fillin': 'Fill-In Digipeater (solo WIDE1-1)',
    'digi_trace_active': 'Activar soporte TRACE',
    'digi_trace_all': 'TRACE también para WIDE2-n y superior',
    'digi_dup_time': 'Duplicar ventana de tiempo de filtro',
    'digi_ports': 'Digipeater activo en el siguiente puerto',
    'digi_hint': 'Nota:\n• Fill-In Digi solo digi-repite WIDE1-1 desde cualquier estación directa .\n• TRACE está destinado a uso experimental. Rutas / tracer .\n• El filtro duplicado previene bucles y repeticiones innecesarias.',
    'igate_settings': 'I-Gate',
    'igate_active': 'Activar I-Gate',
    'igate_rf_to_is': 'RF → APRS-IS (Subida)',
    'igate_is_to_rf': 'APRS-IS → RF (Bajada)',
    'igate_max_distance': 'Maxima distancia para  bajada',
    'igate_local_time': 'La estación es considerada local para',
    'igate_ports': 'Activo en Los siguientes puertos',
    'igate_dup_time': 'Ventana de filtro duplicado',
    'new_pr_mail': 'Nuevo PR-Mail',
    'send': 'Enviar',
    'save_draft': 'Salvar borrador',
    'save_draft_hint1': 'Borrador salvado!',
    'save_draft_hint2': 'El.mensaje ha sido salvado en el borrador.',
    'not_save_draft_hint1': 'Borrador no salvado!',
    'not_save_draft_hint2': 'El borrador no se puede salvar.',
    'del_message_hint1': 'Borrar mensaje?',
    'del_message_hint2': 'Realmente borrar mensaje?',
    'discard': 'Descartar',
    'invalid_call_warning1': 'Direccion incorrecta',
    'invalid_call_warning2': "La  dirección del destinatario es incorrecta. No BBS.",
    'invalid_axcall_warning1': 'Indicativo incorrecto',
    'invalid_axcall_warning2': 'El Indicativo que has introducido es incorrecto.',
    'send_all_now': 'Enviar todo ahora',
    'mark_all_read': 'Marcar como leído',
    'stat_settings': 'Estacion',
    'general_settings': 'General',
    'GPIO': 'GPIO',
    'gpio_fnc_setting_error_1': 'Sin funcion GPIO',
    'gpio_fnc_setting_error_2': 'Sin funcion GPIO asignada!',
    'Digipeater': 'Digipeater',
    'F-Text': 'F-Text',
    'MCast': 'MCast',
    'RX-Echo': 'RX-Echo',
    'new_stat': 'Nueva Estacion',
    'txt_decoding': 'Decodificacion de texto',
    'suc_save': 'Info: Configuración de estacion salvado.',
    'lob1': 'Elogio: Lo hiciste muy bien !!',
    'lob2': 'Elogio: Lo hiciste bien!!',
    'lob3': 'Elogio: Está fue una buena decisión. Sigue así. Lo hiciste bien.',
    'lob4': "Elogio: Hoy no te has ganado ningún elogio.",
    'lob5': "I'm sorry, Dave. I'm afraid I can't do that.",
    'hin1': 'Nota: El botón OK todavía funciona !!',
    'hin2': 'Nota: Cancelado !!',
    'date_time': 'Fecha/Hora',
    'time': 'Hora',
    'date': 'Fecha',
    'message': 'Mensaje',
    'titel': 'Título',
    'from': 'Desde',
    'to': 'Hacia',
    'subject': 'Sujeto',
    'versatz': 'Offset',
    'intervall': 'Intervalo',
    'active': 'Activado',
    'text_fm_file': 'Texto desde Fichero',
    'beacon_settings': 'Baliza',
    'pipetool_settings': 'Ajustes de Pipe-Tool',
    'new_pipe': 'Nuevo Pipe',
    'new_pipe_fm_connection': 'Pipe en Conecxion',
    'tx_file': 'TX Fichero',
    'rx_file': 'RX Fichero',
    'ax25_param': 'AX.25 parametros de conexión',
    'packet_timing_param': 'Paquete y parámetros de temporización',
    'backen_config': 'Configuración del backend',
    'net_ser_opt': 'Red / Opciones serie',
    'serial_interface': 'Interface Serie',
    'port_cfg_std_parm': 'Parametros por Defecto. Se utilizan si no están definidos en ningún otro lugar. (estacion/cliente).',
    'port_cfg_psd_txd': 'Retraso Pseudo TX (tiempo de espera entre TX y RX). No está configurado como un parametro KISS en la TNC.',
    'port_cfg_pac_len': 'Longitud de Paquete. 30-256',
    'port_cfg_pac_max': 'Paquetes Max. 1 - 7',
    'port_cfg_port_name': 'Designacion de puerto para MH y monitor (Max: 4):',
    'port_cfg_not_init': '!! El puerto no está inicializado!!',
    'new_beacon': 'Nueva Baliza',
    'last_packet': 'Ultimo paquete',
    'scrolling': 'Auto scrolling',
    'msg_box_mh_delete': 'Borrar lista MH',
    'msg_box_mh_delete_msg': 'Borrar la listaMH entera?',
    'msg_box_delete_data': 'Borrar datos',
    'msg_box_delete_data_msg': 'Borrar todos los mensajes?',
    'data': 'Datos',
    'multicast_warning': 'Tenga precaución con las conexiones de nodo como TNN. Linkando multiples nodos via multicast puede provocar problemas!',
    'connection_history': 'Historial de Conexión',
    'user_db': 'Base de datos Usuario',
    'show_in_userDB': 'Mostrar en DB-Usuario',
    'cmd_help_bell': 'Llamada a Sysop',
    'cmd_help_wx': 'Estaciones Meteorológicas',
    'cmd_help_user_db': 'Obtener entrada de BD de llamadas',
    'cmd_help_set_name': 'Introducir Nombre',
    'cmd_help_set_qth': 'Introducir QTH',
    'cmd_help_set_loc': 'Introducir Locator',
    'cmd_help_set_zip': 'Introducir Código Postal',
    'cmd_help_set_prmail': 'Introducir Dirección CORREO primario',
    'cmd_help_set_email': 'Introducir dirección E-MAIL',
    'cmd_help_set_http': 'Introducir HTTP',
    'cmd_help_aclear': 'Borrar / Limpiar mensajes APRS',
    'cli_error_no_call': ' # No hay call specifiecado.',
    'cli_error_no_call_in_mh_db': ' # {0} no encontrado en base de datos MH.',
    'cli_error': ' # Error.',
    'cli_no_user_db_ent': ' # Entrada no está enn base de datos usuario!',
    'cli_name_set': ' # Nombre de usuario es definido',
    'cli_qth_set': ' # QTH es definido',
    'cli_loc_set': ' # Locator es definido',
    'cli_zip_set': ' # Código Postal es definido',
    'cli_prmail_set': ' # Direccion PR-Correo es definida',
    'cli_email_set': ' # Dirección E-Mail es definida',
    'cli_http_set': ' # HTTP es definida',
    'cli_text_encoding_no_param': 'Ver/Cambiar la codificación de texto actual',
    'cli_text_encoding_error_not_found': " # No se pudo detectar la codificación de texto correcta.",
    'cli_text_encoding_set': ' # Se detectó/decodificó texto y se estableció en:',
    'port_overview': 'Descripción general del puerto',
    'cmd_shelp': 'Ayuda abreviada',
    'time_connected': 'Duración de conexión',
    'cmd_not_known': 'El Sistema no Conoce este Comando !',
    'auto_text_encoding': 'Detección automática de la codificación de texto. ä como parámetro. > UM ä',
    'cmd_help_lcstatus': 'Muestra canales de terminal conectados (version detallada)',
    'cmd_help_cstat': 'Estadisticas de Conecxión de los Ultimos 7 días',
    'cmd_help_chist': 'Historial de  Conexión (últimos 30 días)',
    'cmd_help_ch': 'Enviar mensaje corto a canal. CH <Channel> Mensaje',
    'cmd_help_rtt': 'Medición del tiempo de ejecución de paquetes',
    'cmd_help_bwstat': 'Band Utilización de Banda últimos 10 minutos',
    'cli_no_wx_data': 'No hay datos WX disponibles',
    'cli_no_data': 'No hay datos disponibles.',
    'cli_no_tracer_data': 'No hay datos Tracerdisponibles ',
    'cli_change_language': 'Cambiar lenguaje.',
    'cli_lang_set': 'Lenguaje cambiado a Ingles.',
    'cli_no_lang_param': 'Lenguaje no reconocido! Posibles lenguajes: ',
    'cmd_rtt_1': ' # Tiempo de viaje de ida y vuelta: ',
    'cmd_bell': 'Llamada al Sysop!!',
    'cmd_bell_again': 'El Sysop ha sido otra vez llamado..',
    'cmd_bell_gui_msg': 'pregunte por el sysop!!',
    'cmd_c_noCall': '# Por favor introduzca llamada..',
    'cmd_c_badCall': '# Destino de Llamada Invalido..',
    'cmd_c_badPort': '# Invalida Especificación de puerto..',
    'cmd_c_noPort': '# Puerto invalido..',
    'ch_cmd_param_error': '# Invalid parameters. CH <Channel> Message',
    'ch_cmd_empty_ch': '# Invalid channel. Channel not connected.',
    'ch_cmd_own_ch': '# Cannot send message to own channel.',
    'ch_cmd_send': '# Message sent to channel {} ({}).\r',
    'cmd_bwstat_1': 'Total bandwidth utilization (last 10 minutes, all ports)',
    'cmd_bwstat_2': 'Band utilization of all ports (%) – 10-minute trend',
    'cmd_bwstat_3': 'Band utilization port {} (%) – 10-minute trend',
    'last_30_days': 'last 30 days',
    'cmd_chist_tab': 'Date       Time     Dur.    Call      Port  Locator / Distance\r',
    'cmd_help_mcast_move_ch': 'Change MCast channel',
    'cmd_help_mcast_ch_info': 'MCast channel info',
    'cmd_help_mcast_channels': 'MCast channel overview',
    'cmd_help_mcast_set_axip': 'Enter/display your own AXIP address',
    'mcast_new_user_beacon': '-= Welcome to the AXIP-MCast Server. Please connect {} to register =-',
    'mcast_new_user_reg_beacon': '-= You have been successfully registered on the MCast server =-\r-= You are on channel {} ({}) =-',
    'mcast_user_enters_channel_beacon': '-= {} has entered the channel =-',
    'mcast_user_left_channel_beacon': '-= {} has left the channel =-',
    'hint_no_mail_for': '\r # No mails available: {}',
    'hint_no_mail': '\r # No mails available',
    'cmd_fwdinfo': 'Shows forward statistics',
    'cmd_r': '<MSG#>: Reads the message with the corresponding number.',
    'cmd_sp': 'SP <Call> @ <BBS>: Sends a personal message to call sign',
    'cmd_sb': 'SB <Category> @ <Distribution>: Sends a bulletin to a category \r              for multiple boxes in a region.',
    'cmd_sr': 'SR <Msg#> : Sends a reply back to the sender\r              of <Msg#> = message number (Send Reply).',
    'cmd_ln': 'Lists all of your own new messages.',
    'cmd_lm': 'Lists all of your own messages.',
    'cmd_ll': '<Number>: Lists the latest news in the specified number.',
    'cmd_l_from': '<CALL>: Lists bulletins FROM a callsign.',
    'cmd_l_to': '<CALL/RUBRIK>: Lists messages TO a call sign or heading.',
    'cmd_l_at': '<CALL>: Lists bulletins VIA distribution.',
    'cmd_lb': 'Lists all bulletin messages.',
    'cmd_km': 'Deletes all personal messages that you have already read.',
    'cmd_k': '<MSG#>: Deletes the message with the corresponding number.',
    'cmd_mr': 'Marks all personal messages as read.',
    'box_cmd_mr_msg': '\r # {} message(s) were marked as read.\r',
    'cmd_op': 'Number of lines per page. Just OP = off.',
    'op_prompt_0': '\r # (A)=Cancel, (O)=continue without stopping, (Return)=continue -->',
    'op_prompt_1': '\r # (A)=Cancel, (R)=Read, (Return)=continue -->',
    'aprs_new_mail_ctext': '\r # APRS: You have {} new message(s). Reading with AMS\r',
    'box_new_mail_ctext': '\r # BOX: You have {} new mails.\r',
    'box_no_hbbs_address': "\r # You haven't entered a home BBS yet. PR <CALL.Distribution>\r",
    'box_cmd_op2': '\r # OP : Error, Invalid Parameter.\r',
    'box_cmd_op1': '\r # OP : No side stop.\r',
    'box_cmd_op3': '\r # OP : Page stop set to {} lines.\r',
    'box_lm_header': 'Msg#  TSLD Byte   To    @ BBS   From   Dat./Time Head\r',
    'box_r_no_msg_found': '\r\r # Message {} not found! \r\r',
    'box_parameter_error': '\r # Error, Invalid Parameter.\r',
    'box_msg_error': '\r # Internal error, cannot read message.\r',
    'box_msg_foter': '\r\r--- End of message #{} to {} from {} BID:{} ---\r\r',
    'box_msg_del': '\r # {} messages have been deleted.\r',
    'box_msg_del_k': '\r # Message(s) {} have been deleted.\r',
    'box_error_no_address': '\r # No recipient specified. SP XX0XX or SP XX0XX@XBBS0.\r',
    'box_error_invalid_dist': '\r # No distribution list in BBS address {}\r',
    'box_cmd_sp_routing_to': '\r # Routing: {}\rTitle of message to {}:\r',
    'box_cmd_sp_local': '\r # Local message.\rTitle of message to {}:\r',
    'box_cmd_sr_enter_msg': 'The answer goes to {}\r',
    'box_cmd_sp_enter_msg': 'Enter text ... (End with /EX or Ctrl-Z):\r',
    'box_cmd_sp_abort_msg': '\r # Message for {} canceled\r\r',
    'box_cmd_sp_msg_accepted': '\r # Ok. Message to address {} @ {} is being forwarded\r   via: {} Mid: {} Bytes: {}\r\r',
    'box_cmd_sp_msg_accepted_local': '\r # Ok. Message to address {} remains local.\r   MID: {} Bytes: {}\r\r',
    'own_station': 'Own station',
    'region': 'Region',
    'fwd_settings': 'Forward',
    'fwd_port_settings': 'FWD-Port',
    'routing_settings': 'Routing',
    'reject_settings': 'Reject/Hold',
    'cc_settings': 'CC',
    'AutoMail_settings': 'Auto Mails',
    'swap_settings': 'SWAP',
    'noConnect': 'No outgoing connect',
    'allowPN_AutoPath': 'Allow PN AutoPath',
    'allowPN_AlterPath': 'Allow PN alternative route',
    'allow_PN_FWD': 'Allow private mail FWD',
    'allow_BL_FWD': 'Allow Bulletin mail FWD',
    'conn_intervall': 'Intervals between connects (minutes): ',
    'conn_timeout': 'Timeout (minutes): ',
    'fwd_autoPath_help': '0 = disabled\n1 = most recent\n2 = best (lowes hops)',
    'bbs_sett_fwd_global': 'Forwarding Global',
    'bbs_sett_local_dist': 'Local distributors',
    'bbs_sett_local_theme': 'Local Bulletin Themes',
    'bbs_sett_block_bbs': 'Block BBS',
    'bbs_sett_block_call': 'Block CALL',
    'bbs_sett_pn_bbs_out': 'Private mail > outgoing',
    'bbs_sett_pn_bbs_in': 'Private mail > incoming',
    'bbs_sett_bl_bbs_in': 'Bulletin mail > incoming',
    'bbs_sett_bl_bbs_out': 'Bulletin mail > outgoing',
    'read_ed': 'read',
    'msgC_sendet_msg': 'Sendet',
    'msgC_trash_bin': 'Trash',
    'saved': 'Saved',
    'private': 'Private',
    'key_title': 'Keyboard layout',
    'key_esc': 'ESC > New connection',
    'key_altc': 'ALT + C > New connection',
    'key_altd': 'ALT + D > Disconnect',
    'key_f': 'F1 - F10 > Channel 1 - 10',
    'key_f12': 'F12 > Monitor',
    'key_strgplus': 'CTRL + plus > Increase text size',
    'key_strgminus': 'CTRL + minus > Reduce text size',
    'key_shiftf': 'SHIFT + F1 - F12 > Macro texts',
    'newcon_title': 'New Connection',
    'ziel': 'Destination',
    'newcon_history': 'History',
    'scheduler': 'Scheduler',
    'type': 'Type:',
    'week_day': 'Week days',
    'month_day': 'Month days',
    'intervall_mn': 'Intervall (mn): ',
    'offset_sec': 'Offset (sec): ',
    'reset': 'Reset',
    'scheduler_set': 'Scheduler set',
    'echo_warning': 'Attention! This function does not replace a digipeater!',
    'mon_start_msg1': 'Info: Station data {} loaded successfully.',
    'mon_start_msg2': 'could not be initialized!',
    'mon_start_msg3': 'initialized successfully.',
    'mon_end_msg1': 'Quiting PoPT.',
    'ENDE':                         'END',
    'FREI':                         'FREE',
    'AUFBAU':                       'INITIALIZE',
    'ABBAU':                        'DISCONNECT',
    'BEREIT':                       'READY',
    'Abgebrochen':                  'Discontinued',
    'Abgebrochen_msg':              'That was a very good decision. \nYou did well, keep it up.',
    'Port_gelöscht':                'Port deleted',
    'Port_gelöscht_msg':            'The Internet has been successfully deleted.',
    'losche_Port':                  'delete port',
    'losche_Port_msg':              'Are you sure you want to delete this port? \nAll settings will be lost!',
    'invalid_call_titel':           'Invalid Callsign',
    'invalid_call_msg':             'The entered sysop-call is invalid',
    'wizard_done':                  'The setup of PoPT is now complete.',
    'wizard_want_port_setup':       'Do you want to set up an AX25 port ?',
    'yes':                          'Yes',
    'no':                           'No',
    'right_level_editor_title':     'Rights Level Editor',
    'glb_rights_txt':               'Global PRP Rights (glb_rights)',
    'new_user_std_level':           'Default level for new users:',
    'allow_remote_access':          'Remote access generally allowed',
    'allow_login':                  'Allow extended rights only after login',
    'edit_rights':                  'Manage Rights Levels',
    'new_level':                    'Add New Level',
    'rename_level':                 'Rename Level',
    'delete_level':                 'Delete Level',
    'with_login':                   'With Login',
    'without_login':                'Without Login',
    'new_level_name':               'Name of the new rights level:',
    'already_exists':               'Already Exists',
    'level_name_already_exists':    "Level '{}' already exists!",
    'error_delete_standard_level':  'The current default level cannot be deleted!',
    'ask_delete_level':             "Really delete rights level '{}'?",
    'new_name':                     'New Name',
    'error':                        'Error',
    'remote_rights':                'Remote Rights',
    'right_level':                  'Rights Level',
    'block_remote_access':          'Completely prohibit remote access (blocked)',
    'individual_rights':            'Individual Rights',
    'password_for_prp_login':       'Access password (for PRP login)',
    'show':                         'Show',
    'aprs_chat_invalid_target':     ' # Invalid call or target (ALL/CQ)',
    'aprs_chat_no_service':         ' # APRS-SMS service not available.',
    'aprs_chat_exit':               ' # APRS Chat ended.',
    'aprs_chat_title':              '=== APRS Chat with {0} on Port {1} via {2} ===',
    'aprs_chat_enter':              'Enter messages directly. //EXIT to leave.',
    'aprs_chat_help':               'Help with //H or //HELP',
    'aprs_msgs_title':              '=== APRS Messages ===',
    'aprs_msgs_more':               '... and more messages',
    'aprs_recent_title':            '--- Latest APRS Messages ({0}) ---',
    'aprs_recent_no_unread':        ' # No unread APRS messages for {0}.',
    'aprs_recent_all_cmd':          'All messages with //AMSGS',
    'aprs_clear_done':              ' # APRS message list cleared.',
    'aprs_chat_help_title':         '=== APRS Chat Help ===',
    'aprs_chat_help_border':        '--------------------------------------------------',
    'aprs_chat_help_h':             '  //H  or  //HELP      - This help',
    'aprs_chat_help_exit':          '  //EXIT or  //Q       - Leave chat',
    'aprs_chat_help_max_hops':      '  //WIDE <HOPS>        - Set maximum hops (1-7) (WIDE[x]-[x])',
    'aprs_chat_help_amsgs':         '  //AMSGS [n]          - Show all messages',
    'aprs_chat_help_aclear':        '  //ACLEAR             - Delete / Clear APRS Messages',
    'aprs_chat_help_achange':       'Change target (without leaving chat):',
    'aprs_chat_help_achat':         '  //ACHAT <Call> [Port]  - Chat with station',
    'aprs_send_error':              ' # Error sending APRS message.'
}
