# SP = Index 10

STR_TABLE_SP = {
    'default_ctext':                "\n-= Hello $destName, =-\n-= welcome to $ownCall ($distance km), =-\n-= on Terminal-Channel $channel <> Port $portNr. =-\n-= That's your connect No. $connNr. =-\n-= $ver - Max-Frame: $parmMaxFrame - Pac-Len: $parmPacLen =-\n\n # Last Login at: $lastConnDate um: $lastConnTime\n\n",
    'default_btext':                '\n73 de $ownCall ...\n',
    'bbs_new_user_reg0':            'Use this BBS as your home BBS? Y/N> ',
    'bbs_new_user_reg_confirm':     'Press <Enter> to confirm or re-enter to change.\r>',
    'bbs_new_user_reg1':            "\rThis is the first connection to this system.\rBefore we continue, please answer the questions. THANK YOU!\rTip: You don't have to put yourself through this, there's something called\rthe Internet.\r\rFirst Name:",
    'bbs_new_user_reg2_1':          'Is {}\rstill your current home BBS? Y/N> ',
    'bbs_new_user_reg2_2':          'Use this BBS as your home BBS? Y/N> ',
    'bbs_new_user_reg3':            'Home-BBS           :',
    'bbs_new_user_reg4':            '\rYou did well!\r\rUser data of $destCall:\rFirst name: {}\rHome BBS  : {}\rQTH       : {}\rLocator   : {}\r\r',
    'bbs_new_user_error_hbbs_add':  '\r # Error, entered call is not a BBS.\r # {} Type is known as {}.\r # Please try again.\r\r',
    'bbs_new_user_sysopMsg_top':    'New user registration',
    'bbs_new_user_sysopMsg_msg':    '{} has just connected to {} for the first time.\nTime: {}\n',
    'language':                     'Language',
    'temperature':                  'Temperature',
    'wx_press':                     'Pressure',
    'wx_hum':                       'Humidity',
    'userdb_add_sysop_ent1':        'Add information?',
    'userdb_add_sysop_ent2':        'Add information from the sysop?',
    'userdb_save_hint':             'Info: User data for {} has been saved.',
    'userdb_del_hint1':             'delete {}?',
    'userdb_del_hint2':             '{} really delete?',
    'userdb_del_hint2_1':           'Delete {} entries?',
    'userdb_del_hint2_2':           'Really delete all {} entries?',
    'userdb_newUser':               'New entry',
    'prewritewin':                  'Prewriting window',
    'consol_log':                   'Log output in the console',
    'call_vali_warning_1':          'Call format!',
    'call_vali_warning_2':          'Max 6 characters only capital letters and numbers.',
    'del_station_hint':             'Note: Station deleted successfully.',
    'del_station_warning_1':        'Station deleted',
    'del_station_warning_2':        'Drive C: was successfully formatted.',
    'del_station_hint_1':           'delete Station',
    'del_station_hint_2':           'Do you really want to delete this station? \nAll settings and texts will be lost!',
    'not_all_station_disco_hint_1': 'Stations not disconnected',
    'not_all_station_disco_hint_2': 'Not all stations are disconnected!',
    'all_station_get_disco_hint_1': 'Stations getting disconnected!',
    'all_station_get_disco_hint_2': 'All stations getting disconnected',
    'close_port':                   'Info: Try to close Port {}.',
    'port_closed':                  'Info: Port {} closed successfully.',
    'send_kiss_parm':               'Note: Kiss parameters sent to TNC on port {}..',
    'port_in_use':                  'Error: Port {} could not be initialized. Port is already in use.',
    'no_port_typ':                  'Note: No port type selected. port {}',
    'port_not_init':                'Error: Port {} could not be initialized.',
    'port_init':                    'Info: Port {} initialized successfully.',
    'setting_saved':                'Info: {}-Settings saved.',
    'all_port_reinit':              'Info: Ports are reinitialized.',
    'port_reinit':                  'Info: Port {} is reinitialized.',
    'all_disco1':                   'Stations are disconnected!',
    'all_disco2':                   'All stations are disconnected',
    'OK':                           'OK',
    'cancel':                       'Cancel',
    'aborted':                      'Aborted',
    'delete':                       'Delete',
    'next':                         'Next',
    'back':                         'Back',
    'delete_selected':              'Delete selection',
    'add':                          'Add',
    'activate':                     'Activate',
    'delete_mh_history':            'Delete MH-List',
    'delete_dx_history':            'Delete DX-Alarm History',
    'delete_tracer_history':        'Delete Trace-History',
    'delete_conn_history':          'Delete Connection-History',
    'del_all':                      'Delete all',
    'select_all':                   'Select all',
    'go':                           'Go',
    'close':                        'Close',
    'save':                         'Save',
    'forward':                      'Forward',
    'answer':                       'Answer',
    'send_file': 'Send File',
    'file_1': 'File',
    'file_2': 'File:',
    'locator_calc': 'Locator Calculator',
    'aprs_mon': 'APRS Monitor',
    'protocol': 'Protocol:',
    'distance': 'Distance',
    'send_if_free': 'Send when band is free for (sec.):',
    'size': 'Size:',
    'new': 'New',
    'wait': 'Wait',
    'new_port': 'New port',
    'new_conn': 'New Connection',
    'disconnect': 'Disconnect',
    'disconnect_all': 'Disconnect ALL',
    'disconnect_all_ask': 'Do you want to disconnect ALL stations?',
    'port_unblock_all': 'Allow incoming connections (all ports)',
    'port_block_ignore_all': 'Ignore incoming connections (all ports)',
    'port_block_reject_all': 'Reject incoming connections (all ports)',
    'wx_window': 'Weather Stations',
    'quit': 'Quit',
    'connections': 'Connections',
    'copy': 'Copy',
    'past': 'Past',
    'cut': 'Cut out',
    'past_f_file': 'Past from File',
    'save_to_file': 'Save to File',
    'past_qso_f_file': 'Past from File',
    'save_qso_to_file': 'Save QSO to File',
    'save_mon_to_file': 'Save Monitor to File',
    'clean_prescription_win': 'Clear Prescription window',
    'clean_just_qso_win': 'Clear QSO window',
    'clean_qso_win': 'Clear QSO/Prescription window',
    'clean_all_qso_win': 'Clear all QSO/Prescription window',
    'send_selected': 'Send selected',
    'clean_mon_win': 'Clear Monitor',
    'edit': 'Edit',
    'statistic': 'Statistics',
    'history': 'History',
    'linkholder': 'Link holder',
    'right_level_editor': 'Rights Level Editor',
    'clean_qso': 'delete QSO',
    'tools': 'Tools',
    'station': 'Station',
    'stations': 'Stations',
    'port': 'Port',
    'address': 'Address',
    'channel': 'Channel',
    'beacon': 'Beacons',
    'sprech': 'Speech output',
    'settings': 'Settings',
    'main_page': 'Main Page',
    'password': 'Password',
    'passwords': 'Passwords',
    'syspassword': 'Sys-Password:',
    'trys': 'Fake-Attempts:',
    'fillchars': 'Response length:',
    'priv': 'Login',
    'login_cmd': 'Login Command:',
    'command': 'Command',
    'keybind': 'Keyboard layout',
    'about': 'About',
    'help': 'Help',
    'number': 'Number',
    'seconds': 'Second(s)',
    'minutes': 'Minute(s)',
    'hours': 'Hours',
    'day': 'Day',
    'month': 'Month',
    'occup': 'Occupancy in %',
    'call': 'Call',
    'name': 'Name',
    'fwd_list': 'Forward queue',
    'fwd_path': 'Forward routes',
    'start_fwd': 'FWD start',
    'start_auto_fwd': 'AutoFWD start',
    'msg_center': 'Message Center',
    'text_winPos': 'Text window position (top/middle/bottom)',
    'qso_win_color': 'QSO Win Color',
    'text_color': 'Text Color',
    'bg_color': 'Backgrund Color',
    'backgrund': 'Backgrund',
    'mon_color': 'Monitor Colors',
    'c_text': 'C Text',
    'q_text': 'Quit Text',
    'i_text': 'Info Text',
    'li_text': 'Long-Info Text',
    'news_text': 'News Text',
    'comment': 'Comment',
    'aprs_settings': 'APRS-Settings',
    'digi_settings': 'DIGI-Settings',
    'aprs_server': 'APRS-Server',
    'conn_2_aprs_server': 'Connect to APRS server',
    'aprs_pn_msg': 'APRS Messenger',
    'pn_msg': 'Private Messages',
    'msg': 'Message',
    'new_msg': 'New Message',
    'aprs_digi_settings': 'Digipeater',
    'aprs_tracer_settings': 'Tracer',
    'digi_active': 'Enable APRS Digipeater',
    'digi_fillin': 'Fill-In Digipeater (WIDE1-1 only)',
    'digi_trace_active': 'Enable TRACE support',
    'digi_trace_all': 'TRACE also for WIDE2-n and higher',
    'digi_dup_time': 'Duplicate filter time window',
    'digi_ports': 'Digipeater active on the following ports',
    'digi_hint': 'Note:\n• Fill-In Digi only digipeats WIDE1-1 from direct stations.\n• TRACE is intended for experimental / tracer paths.\n• The duplicate filter prevents loops and unnecessary repetitions.',
    'igate_settings': 'I-Gate',
    'igate_active': 'Enable I-Gate',
    'igate_rf_to_is': 'RF → APRS-IS (Upload)',
    'igate_is_to_rf': 'APRS-IS → RF (Downlink)',
    'igate_max_distance': 'Maximum distance for Downlink',
    'igate_local_time': 'Station is considered local for',
    'igate_ports': 'Active on the following ports',
    'igate_dup_time': 'Duplicate filter time window',
    'new_pr_mail': 'New PR-Mail',
    'send': 'Send',
    'save_draft': 'Save draft',
    'save_draft_hint1': 'Draft saved!',
    'save_draft_hint2': 'Message was saved as a draft.',
    'not_save_draft_hint1': 'Draft not saved!',
    'not_save_draft_hint2': 'Draft could not be saved.',
    'del_message_hint1': 'Delete message?',
    'del_message_hint2': 'Really delete message?',
    'discard': 'Discard',
    'invalid_call_warning1': 'Address incorrect',
    'invalid_call_warning2': "The recipient's address is incorrect. No BBS.",
    'invalid_axcall_warning1': 'Call incorrect',
    'invalid_axcall_warning2': 'The call you entered is incorrect.',
    'send_all_now': 'Send everything now',
    'mark_all_read': 'Mark all as read',
    'stat_settings': 'Station',
    'general_settings': 'General',
    'GPIO': 'GPIO',
    'gpio_fnc_setting_error_1': 'No GPIO function',
    'gpio_fnc_setting_error_2': 'No GPIO function assigned!',
    'Digipeater': 'Digipeater',
    'F-Text': 'F-Text',
    'MCast': 'MCast',
    'RX-Echo': 'RX-Echo',
    'new_stat': 'New Station',
    'txt_decoding': 'Text decoding',
    'suc_save': 'Info: Station setiings saved.',
    'lob1': 'Praise: You did very well !!',
    'lob2': 'Praise: You did well!!',
    'lob3': 'Praise: That was a good decision. Keep it up. You did well.',
    'lob4': "Praise: You haven't earned any praise today.",
    'lob5': "I'm sorry, Dave. I'm afraid I can't do that.",
    'hin1': 'Note: The OK button still works !!',
    'hin2': 'Note: Canceled !!',
    'date_time': 'Date/Time',
    'time': 'Time',
    'date': 'Date',
    'message': 'Message',
    'titel': 'Title',
    'from': 'From',
    'to': 'To',
    'subject': 'Subject',
    'versatz': 'Offset',
    'intervall': 'Interval',
    'active': 'Activated',
    'text_fm_file': 'Text from File',
    'beacon_settings': 'Beacon',
    'pipetool_settings': 'Pipe-Tool Settings',
    'new_pipe': 'New Pipe',
    'new_pipe_fm_connection': 'Pipe on Connection',
    'tx_file': 'TX File',
    'rx_file': 'RX File',
    'ax25_param': 'AX.25 connection parameters',
    'packet_timing_param': 'Package & timing parameters',
    'backen_config': 'Backend configuration',
    'net_ser_opt': 'Network / Serial Options',
    'serial_interface': 'Serial interface',
    'port_cfg_std_parm': 'Default parameters. Are used if not defined anywhere else (station/client).',
    'port_cfg_psd_txd': 'Pseudo TX delay (waiting time between TX and RX). Is not set as a KISS parameter on the TNC.',
    'port_cfg_pac_len': 'Packet length. 30-256',
    'port_cfg_pac_max': 'Max Packets. 1 - 7',
    'port_cfg_port_name': 'Port designation for MH and monitor (Max: 4):',
    'port_cfg_not_init': '!! Port is not initialized!!',
    'new_beacon': 'New Beacon',
    'last_packet': 'last packet',
    'scrolling': 'Auto scrolling',
    'msg_box_mh_delete': 'Delete MH list',
    'msg_box_mh_delete_msg': 'Delete entire MH list?',
    'msg_box_delete_data': 'Delete data',
    'msg_box_delete_data_msg': 'Delete all data?',
    'data': 'Data',
    'multicast_warning': 'Be careful with node connections like TNN. Linking multiple nodes via multicast can lead to problems!',
    'connection_history': 'Connection history',
    'user_db': 'User Database',
    'show_in_userDB': 'Show in User-DB',
    'cmd_help_bell': 'Call Sysop',
    'cmd_help_wx': 'Weather stations',
    'cmd_help_user_db': 'Get Call DB entry',
    'cmd_help_set_name': 'Enter Name',
    'cmd_help_set_qth': 'Enter QTH',
    'cmd_help_set_loc': 'Enter Locator',
    'cmd_help_set_zip': 'Enter ZIP',
    'cmd_help_set_prmail': 'Enter PR-MAIL Address',
    'cmd_help_set_email': 'Enter E-MAIL Address',
    'cmd_help_set_http': 'Enter HTTP',
    'cmd_help_aclear': 'Delete / Clear APRS Messages',
    'cli_error_no_call': ' # No call specified.',
    'cli_error_no_call_in_mh_db': ' # {0} not found in MH database.',
    'cli_error': ' # Error.',
    'cli_no_user_db_ent': ' # Entry not in user database!',
    'cli_name_set': ' # Username is set',
    'cli_qth_set': ' # QTH is set',
    'cli_loc_set': ' # Locator is set',
    'cli_zip_set': ' # ZIP is set',
    'cli_prmail_set': ' # PR-Mail Address is set',
    'cli_email_set': ' # E-Mail Address is set',
    'cli_http_set': ' # HTTP is set',
    'cli_text_encoding_no_param': ' # Please send an ä. Example: UM ä.\r # Current setting:',
    'cli_text_encoding_error_not_found': " # Couldn't detect right text encoding",
    'cli_text_encoding_set': ' # Text de/encoding set to:',
    'cli_text_encoding_current': 'Currently used encoder',
    'cli_text_encoding_cmd_help': 'Set text encoding with ENC <opt>',
    'port_overview': 'Port Overview',
    'cmd_shelp': 'Short help',
    'time_connected': 'Connect duration',
    'cmd_not_known': 'The system does not know this command !',
    'auto_text_encoding': 'Automatic detection of text encoding. ä as a parameter. > UM ä',
    'cmd_help_lcstatus': 'Show connected terminal channels (detailed version)',
    'cmd_help_cstat': 'Connection statistics for the last 7 days',
    'cmd_help_chist': 'Connection History (last 30 days)',
    'cmd_help_ch': 'Send short message to channel. CH <Channel> Message',
    'cmd_help_rtt': 'Packet runtime measurement',
    'cmd_help_bwstat': 'Band utilization last 10 minutes',
    'cli_no_wx_data': 'No WX data available',
    'cli_no_data': 'No data available.',
    'cli_no_tracer_data': 'No Tracer data available',
    'cli_change_language': 'Change language.',
    'cli_lang_set': 'Language changed to English.',
    'cli_no_lang_param': 'Language not recognized! Possible languages: ',
    'cmd_rtt_1': ' # Round trip time: ',
    'cmd_bell': 'Sysop is called!!',
    'cmd_bell_again': 'Sysop has already been called..',
    'cmd_bell_gui_msg': 'asks for the sysop!!',
    'cmd_c_noCall': '# Please enter call..',
    'cmd_c_badCall': '# Invalid destination call..',
    'cmd_c_badPort': '# Invalid port specification..',
    'cmd_c_noPort': '# Invalid port..',
    'ch_cmd_param_error': '# Invalid parameters. CH <Channel> Message',
    'ch_cmd_empty_ch': '# Invalid channel. Channel not connected.',
    'ch_cmd_own_ch': '# Cannot send message to own channel.',
    'ch_cmd_send': '# Message sent to channel {} ({}).\r',
    'cmd_bwstat_1': 'Total bandwidth utilization (last 10 minutes, all ports)',
    'cmd_bwstat_2': 'Band utilization of all ports (%) – 10-minute trend',
    'cmd_bwstat_3': 'Band utilization port {} (%) – 10-minute trend',
    'last_30_days': 'last 30 days',
    'cmd_chist_tab': 'Date       Time     Dur.    Call      Port  Locator / Distance\r',
    'cmd_help_mcast_move_ch': 'Change MCast channel',
    'cmd_help_mcast_ch_info': 'MCast channel info',
    'cmd_help_mcast_channels': 'MCast channel overview',
    'cmd_help_mcast_set_axip': 'Enter/display your own AXIP address',
    'mcast_new_user_beacon': '-= Welcome to the AXIP-MCast Server. Please connect {} to register =-',
    'mcast_new_user_reg_beacon': '-= You have been successfully registered on the MCast server =-\r-= You are on channel {} ({}) =-',
    'mcast_user_enters_channel_beacon': '-= {} has entered the channel =-',
    'mcast_user_left_channel_beacon': '-= {} has left the channel =-',
    'hint_no_mail_for': '\r # No mails available: {}',
    'hint_no_mail': '\r # No mails available',
    'cmd_fwdinfo': 'Shows forward statistics',
    'cmd_r': '<MSG#>: Reads the message with the corresponding number.',
    'cmd_sp': 'SP <Call> @ <BBS>: Sends a personal message to call sign',
    'cmd_sb': 'SB <Category> @ <Distribution>: Sends a bulletin to a category \r              for multiple boxes in a region.',
    'cmd_sr': 'SR <Msg#> : Sends a reply back to the sender\r              of <Msg#> = message number (Send Reply).',
    'cmd_ln': 'Lists all of your own new messages.',
    'cmd_lm': 'Lists all of your own messages.',
    'cmd_ll': '<Number>: Lists the latest news in the specified number.',
    'cmd_l_from': '<CALL>: Lists bulletins FROM a callsign.',
    'cmd_l_to': '<CALL/RUBRIK>: Lists messages TO a call sign or heading.',
    'cmd_l_at': '<CALL>: Lists bulletins VIA distribution.',
    'cmd_lb': 'Lists all bulletin messages.',
    'cmd_km': 'Deletes all personal messages that you have already read.',
    'cmd_k': '<MSG#>: Deletes the message with the corresponding number.',
    'cmd_mr': 'Marks all personal messages as read.',
    'box_cmd_mr_msg': '\r # {} message(s) were marked as read.\r',
    'cmd_op': 'Number of lines per page. Just OP = off.',
    'op_prompt_0': '\r # (A)=Cancel, (O)=continue without stopping, (Return)=continue -->',
    'op_prompt_1': '\r # (A)=Cancel, (R)=Read, (Return)=continue -->',
    'aprs_new_mail_ctext': '\r # APRS: You have {} new message(s). Reading with AMS\r',
    'box_new_mail_ctext': '\r # BOX: You have {} new mails.\r',
    'box_no_hbbs_address': "\r # You haven't entered a home BBS yet. PR <CALL.Distribution>\r",
    'box_cmd_op2': '\r # OP : Error, Invalid Parameter.\r',
    'box_cmd_op1': '\r # OP : No side stop.\r',
    'box_cmd_op3': '\r # OP : Page stop set to {} lines.\r',
    'box_lm_header': 'Msg#  TSLD Byte   To    @ BBS   From   Dat./Time Head\r',
    'box_r_no_msg_found': '\r\r # Message {} not found! \r\r',
    'box_parameter_error': '\r # Error, Invalid Parameter.\r',
    'box_msg_error': '\r # Internal error, cannot read message.\r',
    'box_msg_foter': '\r\r--- End of message #{} to {} from {} BID:{} ---\r\r',
    'box_msg_del': '\r # {} messages have been deleted.\r',
    'box_msg_del_k': '\r # Message(s) {} have been deleted.\r',
    'box_error_no_address': '\r # No recipient specified. SP XX0XX or SP XX0XX@XBBS0.\r',
    'box_error_invalid_dist': '\r # No distribution list in BBS address {}\r',
    'box_cmd_sp_routing_to': '\r # Routing: {}\rTitle of message to {}:\r',
    'box_cmd_sp_local': '\r # Local message.\rTitle of message to {}:\r',
    'box_cmd_sr_enter_msg': 'The answer goes to {}\r',
    'box_cmd_sp_enter_msg': 'Enter text ... (End with /EX or Ctrl-Z):\r',
    'box_cmd_sp_abort_msg': '\r # Message for {} canceled\r\r',
    'box_cmd_sp_msg_accepted': '\r # Ok. Message to address {} @ {} is being forwarded\r   via: {} Mid: {} Bytes: {}\r\r',
    'box_cmd_sp_msg_accepted_local': '\r # Ok. Message to address {} remains local.\r   MID: {} Bytes: {}\r\r',
    'own_station': 'Own station',
    'region': 'Region',
    'fwd_settings': 'Forward',
    'fwd_port_settings': 'FWD-Port',
    'routing_settings': 'Routing',
    'reject_settings': 'Reject/Hold',
    'cc_settings': 'CC',
    'AutoMail_settings': 'Auto Mails',
    'swap_settings': 'SWAP',
    'noConnect': 'No outgoing connect',
    'allowPN_AutoPath': 'Allow PN AutoPath',
    'allowPN_AlterPath': 'Allow PN alternative route',
    'allow_PN_FWD': 'Allow private mail FWD',
    'allow_BL_FWD': 'Allow Bulletin mail FWD',
    'conn_intervall': 'Intervals between connects (minutes): ',
    'conn_timeout': 'Timeout (minutes): ',
    'fwd_autoPath_help': '0 = disabled\n1 = most recent\n2 = best (lowes hops)',
    'bbs_sett_fwd_global': 'Forwarding Global',
    'bbs_sett_local_dist': 'Local distributors',
    'bbs_sett_local_theme': 'Local Bulletin Themes',
    'bbs_sett_block_bbs': 'Block BBS',
    'bbs_sett_block_call': 'Block CALL',
    'bbs_sett_pn_bbs_out': 'Private mail > outgoing',
    'bbs_sett_pn_bbs_in': 'Private mail > incoming',
    'bbs_sett_bl_bbs_in': 'Bulletin mail > incoming',
    'bbs_sett_bl_bbs_out': 'Bulletin mail > outgoing',
    'read_ed': 'read',
    'msgC_sendet_msg': 'Sendet',
    'msgC_trash_bin': 'Trash',
    'saved': 'Saved',
    'private': 'Private',
    'key_title': 'Keyboard layout',
    'key_esc': 'ESC > New connection',
    'key_altc': 'ALT + C > New connection',
    'key_altd': 'ALT + D > Disconnect',
    'key_f': 'F1 - F10 > Channel 1 - 10',
    'key_f12': 'F12 > Monitor',
    'key_strgplus': 'CTRL + plus > Increase text size',
    'key_strgminus': 'CTRL + minus > Reduce text size',
    'key_shiftf': 'SHIFT + F1 - F12 > Macro texts',
    'newcon_title': 'New Connection',
    'ziel': 'Destination',
    'newcon_history': 'History',
    'scheduler': 'Scheduler',
    'type': 'Type:',
    'week_day': 'Week days',
    'month_day': 'Month days',
    'intervall_mn': 'Intervall (mn): ',
    'offset_sec': 'Offset (sec): ',
    'reset': 'Reset',
    'scheduler_set': 'Scheduler set',
    'echo_warning': 'Attention! This function does not replace a digipeater!',
    'mon_start_msg1': 'Info: Station data {} loaded successfully.',
    'mon_start_msg2': 'could not be initialized!',
    'mon_start_msg3': 'initialized successfully.',
    'mon_end_msg1': 'Quiting PoPT.',
    'ENDE':                         'END',
    'FREI':                         'FREE',
    'AUFBAU':                       'INITIALIZE',
    'ABBAU':                        'DISCONNECT',
    'BEREIT':                       'READY',
    'Abgebrochen':                  'Discontinued',
    'Abgebrochen_msg':              'That was a very good decision. \nYou did well, keep it up.',
    'Port_gelöscht':                'Port deleted',
    'Port_gelöscht_msg':            'The Internet has been successfully deleted.',
    'losche_Port':                  'delete port',
    'losche_Port_msg':              'Are you sure you want to delete this port? \nAll settings will be lost!',
    'invalid_call_titel':           'Invalid Callsign',
    'invalid_call_msg':             'The entered sysop-call is invalid',
    'wizard_done':                  'The setup of PoPT is now complete.',
    'wizard_want_port_setup':       'Do you want to set up an AX25 port ?',
    'yes':                          'Yes',
    'no':                           'No',
    'right_level_editor_title':     'Rights Level Editor',
    'glb_rights_txt':               'Global PRP Rights (glb_rights)',
    'new_user_std_level':           'Default level for new users:',
    'allow_remote_access':          'Remote access generally allowed',
    'allow_login':                  'Allow extended rights only after login',
    'edit_rights':                  'Manage Rights Levels',
    'new_level':                    'Add New Level',
    'rename_level':                 'Rename Level',
    'delete_level':                 'Delete Level',
    'with_login':                   'With Login',
    'without_login':                'Without Login',
    'new_level_name':               'Name of the new rights level:',
    'already_exists':               'Already Exists',
    'level_name_already_exists':    "Level '{}' already exists!",
    'error_delete_standard_level':  'The current default level cannot be deleted!',
    'ask_delete_level':             "Really delete rights level '{}'?",
    'new_name':                     'New Name',
    'error':                        'Error',
    'remote_rights':                'Remote Rights',
    'right_level':                  'Rights Level',
    'block_remote_access':          'Completely prohibit remote access (blocked)',
    'individual_rights':            'Individual Rights',
    'password_for_prp_login':       'Access password (for PRP login)',
    'show':                         'Show',
    'aprs_chat_invalid_target':     ' # Invalid call or target (ALL/CQ)',
    'aprs_chat_no_service':         ' # APRS-SMS service not available.',
    'aprs_chat_exit':               ' # APRS Chat ended.',
    'aprs_chat_title':              '=== APRS Chat with {0} on Port {1} via {2} ===',
    'aprs_chat_enter':              'Enter messages directly. //EXIT to leave.',
    'aprs_chat_help':               'Help with //H or //HELP',
    'aprs_msgs_title':              '=== APRS Messages ===',
    'aprs_msgs_more':               '... and more messages',
    'aprs_recent_title':            '--- Latest APRS Messages ({0}) ---',
    'aprs_recent_no_unread':        ' # No unread APRS messages for {0}.',
    'aprs_recent_all_cmd':          'All messages with //AMSGS',
    'aprs_clear_done':              ' # APRS message list cleared.',
    'aprs_chat_help_title':         '=== APRS Chat Help ===',
    'aprs_chat_help_border':        '--------------------------------------------------',
    'aprs_chat_help_h':             '  //H  or  //HELP      - This help',
    'aprs_chat_help_exit':          '  //EXIT or  //Q       - Leave chat',
    'aprs_chat_help_max_hops':      '  //WIDE <HOPS>        - Set maximum hops (1-7) (WIDE[x]-[x])',
    'aprs_chat_help_amsgs':         '  //AMSGS [n]          - Show all messages',
    'aprs_chat_help_aclear':        '  //ACLEAR             - Delete / Clear APRS Messages',
    'aprs_chat_help_achange':       'Change target (without leaving chat):',
    'aprs_chat_help_achat':         '  //ACHAT <Call> [Port]  - Chat with station',
    'aprs_send_error':              ' # Error sending APRS message.',
    'default_text':                 'Default Text',
}
