"""
0: 'de'
1: 'en'
2: 'nl'
3: 'fr'
4: 'fi'
5: 'pl'
6: 'pt'
7: 'it'
8: 'zh'     # Not really ;-)
9: '?'

Thanks to NL1NOD(Patrick) for the Dutch translations.
"""

STR_TABLE = {
    #  GER
    #  ENG
    #  NL
    #  FR
    #  FI
    #  PL
    #  PT
    #  IT
    #  ?
    #  ?
    'default_ctext': (
        # GER
        ('\n'
       '-= Hallo $destName, =-\n' 
       '-= willkommen bei $ownCall ($distance km), =-\n'
       '-= auf Terminal-Kanal $channel <> Port $portNr. =-\n'
       '-= Das ist Connect Nr. $connNr. =-\n'
       '-= $ver - Max-Frame: $parmMaxFrame - Pac-Len: $parmPacLen =-\n'
       '\n'
       ' # Letzer Login am: $lastConnDate um: $lastConnTime\n'
       '\n'),
        # ENG
        ('\n'
       '-= Hello $destName, =-\n' 
       '-= welcome to $ownCall ($distance km), =-\n'
       '-= on Terminal-Channel $channel <> Port $portNr. =-\n'
       "-= That's your connect No. $connNr. =-\n"
       '-= $ver - Max-Frame: $parmMaxFrame - Pac-Len: $parmPacLen =-\n'
       '\n'
       ' # Last Login at: $lastConnDate um: $lastConnTime\n'
       '\n'),
        # NL
        ('\n'
       '-= Hallo $destName, =-\n' 
       '-= willkommen bei $ownCall ($distance km), =-\n'
       '-= auf Terminal-Kanal $channel <> Port $portNr. =-\n'
       '-= Das ist Connect Nr. $connNr. =-\n'
       '-= $ver - Max-Frame: $parmMaxFrame - Pac-Len: $parmPacLen =-\n'
       '\n'
       ' # Letzer Login am: $lastConnDate um: $lastConnTime\n'
       '\n'),
        # FR
        ('\n'
       '-= Hallo $destName, =-\n' 
       '-= willkommen bei $ownCall ($distance km), =-\n'
       '-= auf Terminal-Kanal $channel <> Port $portNr. =-\n'
       '-= Das ist Connect Nr. $connNr. =-\n'
       '-= $ver - Max-Frame: $parmMaxFrame - Pac-Len: $parmPacLen =-\n'
       '\n'
       ' # Letzer Login am: $lastConnDate um: $lastConnTime\n'
       '\n'),
        # FI
        ('\n'
       '-= Hallo $destName, =-\n' 
       '-= willkommen bei $ownCall ($distance km), =-\n'
       '-= auf Terminal-Kanal $channel <> Port $portNr. =-\n'
       '-= Das ist Connect Nr. $connNr. =-\n'
       '-= $ver - Max-Frame: $parmMaxFrame - Pac-Len: $parmPacLen =-\n'
       '\n'
       ' # Letzer Login am: $lastConnDate um: $lastConnTime\n'
       '\n'),
        # PL
        ('\n'
       '-= Hallo $destName, =-\n' 
       '-= willkommen bei $ownCall ($distance km), =-\n'
       '-= auf Terminal-Kanal $channel <> Port $portNr. =-\n'
       '-= Das ist Connect Nr. $connNr. =-\n'
       '-= $ver - Max-Frame: $parmMaxFrame - Pac-Len: $parmPacLen =-\n'
       '\n'
       ' # Letzer Login am: $lastConnDate um: $lastConnTime\n'
       '\n'),
        # PT
        ('\n'
       '-= Hallo $destName, =-\n' 
       '-= willkommen bei $ownCall ($distance km), =-\n'
       '-= auf Terminal-Kanal $channel <> Port $portNr. =-\n'
       '-= Das ist Connect Nr. $connNr. =-\n'
       '-= $ver - Max-Frame: $parmMaxFrame - Pac-Len: $parmPacLen =-\n'
       '\n'
       ' # Letzer Login am: $lastConnDate um: $lastConnTime\n'
       '\n'),
        # IT
        ('\n'
       '-= Hallo $destName, =-\n' 
       '-= willkommen bei $ownCall ($distance km), =-\n'
       '-= auf Terminal-Kanal $channel <> Port $portNr. =-\n'
       '-= Das ist Connect Nr. $connNr. =-\n'
       '-= $ver - Max-Frame: $parmMaxFrame - Pac-Len: $parmPacLen =-\n'
       '\n'
       ' # Letzer Login am: $lastConnDate um: $lastConnTime\n'
       'v'),
        # ??????
        ('\n'
       '-= Hallo $destName, =-\n' 
       '-= willkommen bei $ownCall ($distance km), =-\n'
       '-= auf Terminal-Kanal $channel <> Port $portNr. =-\n'
       '-= Das ist Connect Nr. $connNr. =-\n'
       '-= $ver - Max-Frame: $parmMaxFrame - Pac-Len: $parmPacLen =-\n'
       '\n'
       ' # Letzer Login am: $lastConnDate um: $lastConnTime\n'
       '\n'),
        # ??????
        ('\n'
       '-= Hallo $destName, =-\n' 
       '-= willkommen bei $ownCall ($distance km), =-\n'
       '-= auf Terminal-Kanal $channel <> Port $portNr. =-\n'
       '-= Das ist Connect Nr. $connNr. =-\n'
       '-= $ver - Max-Frame: $parmMaxFrame - Pac-Len: $parmPacLen =-\n'
       '\n'
       ' # Letzer Login am: $lastConnDate um: $lastConnTime\n'
       '\n'),
    ),

    'default_btext': (
        '\n73 de $ownCall ...\n',
        '\n73 de $ownCall ...\n',
        '\n73 de $ownCall ...\n',
        '\n73 de $ownCall ...\n',
        '\n73 de $ownCall ...\n',
        '\n73 de $ownCall ...\n',
        '\n73 de $ownCall ...\n',
        '\n73 de $ownCall ...\n',
        '\n73 de $ownCall ...\n',
        '\n73 de $ownCall ...\n'),

    'language': (
        'Sprache',
        'Language',
        'Taal',
        '',
        '',
        '',
        '',
        '',
        '',
        ''),

    'userdb_add_sysop_ent1': (
        'Informationen ergänzen?',
        'Add information?',
        'Informatie toevoegen?',
        '',
        '',
        '',
        '',
        '',
        '',
        ''),

    'userdb_add_sysop_ent2': (
        'Einträge vom Sysop ergänzen ?',
        'Add information from the sysop?',
        'Informatie uit de sysop toevoegen?',
        '',
        '',
        '',
        '',
        '',
        '',
        ''),

    'userdb_save_hint': (
        'Info: User Daten für {} wurden gespeichert..',
        'Info: User data for {} has been saved.',
        'Info: gebruikersgegevens voor {} zijn opgeslagen.',
        '',
        '',
        '',
        '',
        '',
        '',
        ''),

    'userdb_del_hint1': (
        'lösche',
        'delete',
        'verwijderen',
        '',
        '',
        '',
        '',
        '',
        '',
        ''),

    'userdb_del_hint2': (
        'löschen',
        'delete',
        'verwijderen',
        '',
        '',
        '',
        '',
        '',
        '',
        ''),

    'userdb_newUser': (
        'Neuer Eintrag',
        'New entry',
        'Nieuwe invoer',
        '',
        '',
        '',
        '',
        '',
        '',
        ''),

    'prewritewin': (
        'Vorschreibfenster',
        'Prewriting window',
        'Voorschrijfvenster',
        '',
        '',
        '',
        '',
        '',
        '',
        ''),

    'call_vali_warning_1': (
        'Call Format!',
        'Call format!',
        '-----------',
        '',
        '',
        '',
        '',
        '',
        '',
        ''),

    'call_vali_warning_2': (
        'Max 6 Zeichen nur Großbuchstaben und Zahlen.',
        'Max 6 characters only capital letters and numbers.',
        '-----------',
        '',
        '',
        '',
        '',
        '',
        '',
        ''),

    'del_station_hint': (
        'Hinweis: Station erfolgreich gelöscht.',
        'Note: Station deleted successfully.',
        'Opmerking: Zender is succesvol verwijderd.',
        '',
        '',
        '',
        '',
        '',
        '',
        ''),

    'del_station_warning_1': (
        'Station gelöscht',
        'Station deleted',
        'Zender verwijderd',
        '',
        '',
        '',
        '',
        '',
        '',
        ''),

    'del_station_warning_2': (
        'Laufwerk C: wurde erfolgreich formatiert.',
        'Drive C: was successfully formatted.',
        'Schijf C: is succesvol geformatteerd.',
        '',
        '',
        '',
        '',
        '',
        '',
        ''),

    'del_station_hint_1': (
        'lösche Station',
        'delete Station',
        '-----------',
        '',
        '',
        '',
        '',
        '',
        '',
        ''),

    'del_station_hint_2': (
        'Willst du diese Station wirklich löschen? \nAlle Einstellungen sowie Texte gehen verloren !',
        'Do you really want to delete this station? \nAll settings and texts will be lost!',
        'Wilt u deze zender echt verwijderen? \nAlle instellingen en teksten gaan verloren!',
        '',
        '',
        '',
        '',
        '',
        '',
        ''),

    'not_all_station_disco_hint_1': (
        'Stationen nicht disconnected',
        'Stations not disconnected',
        '-----------',
        '',
        '',
        '',
        '',
        '',
        '',
        ''),

    'not_all_station_disco_hint_2': (
        'Nicht alle Stationen disconnected!',
        'Not all stations are disconnected!',
        '-----------',
        '',
        '',
        '',
        '',
        '',
        '',
        ''),

    'all_station_get_disco_hint_1': (
        'Stationen werden disconnected !',
        'Stations getting disconnected!',
        '-----------',
        '',
        '',
        '',
        '',
        '',
        '',
        ''),

    'all_station_get_disco_hint_2': (
        'Es werden alle Stationen disconnected',
        'All stations getting disconnected',
        '-----------',
        '',
        '',
        '',
        '',
        '',
        '',
        ''),

    'close_port': ('Info: Versuche Port {} zu schließen.',
           'Info: Try to close Port {}.',
           '-----------',
           '',
           '',
           '',
           '',
           '',
           '',
           ''),

    'port_closed': ('Info: Port {} erfolgreich geschlossen.',
           'Info: Port {} closed successfully.',
           '-----------',
           '',
           '',
           '',
           '',
           '',
           '',
           ''),

    'send_kiss_parm': ('Hinweis: Kiss-Parameter an TNC auf Port {} gesendet..',
           'Note: Kiss parameters sent to TNC on port {}..',
           '-----------',
           '',
           '',
           '',
           '',
           '',
           '',
           ''),

    'port_in_use': ('Error: Port {} konnte nicht initialisiert werden. Port wird bereits benutzt.',
           'Error: Port {} could not be initialized. Port is already in use.',
           '-----------',
           '',
           '',
           '',
           '',
           '',
           '',
           ''),

    'no_port_typ': ('Hinweis: Kein Port-Typ ausgewählt. Port {}',
           'Note: No port type selected. port {}',
           '-----------',
           '',
           '',
           '',
           '',
           '',
           '',
           ''),

    'port_not_init': ('Error: Port {} konnte nicht initialisiert werden.',
           'Error: Port {} could not be initialized.',
           '-----------',
           '',
           '',
           '',
           '',
           '',
           '',
           ''),
    'port_init': ('Info: Port {} erfolgreich initialisiert.',
           'Info: Port {} initialized successfully.',
           '-----------',
           '',
           '',
           '',
           '',
           '',
           '',
           ''),

    'setting_saved': (
           'Info: {}-Einstellungen wurden gespeichert.',
           'Info: {}-Settings saved.',
           '-----------',
           '',
           '',
           '',
           '',
           '',
           '',
           ''),

    'all_port_reinit': (
           'Info: Ports werden reinitialisiert.',
           'Info: Ports are reinitialized.',
           '-----------',
           '',
           '',
           '',
           '',
           '',
           '',
           ''),

    'port_reinit': (
           'Info: Port {} wird reinitialisiert.',
           'Info: Port {} is reinitialized.',
           '-----------',
           '',
           '',
           '',
           '',
           '',
           '',
           ''),

    'all_disco1': (
           'Stationen werden disconnected !',
           'Stations are disconnected!',
           'Stations zijn losgekoppeld!',
           '',
           '',
           '',
           '',
           '',
           '',
           ''),
    'all_disco2': (
           'Es werden alle Stationen disconnected',
           'All stations are disconnected',
           'Alle stations zijn losgekoppeld',
           '',
           '',
           '',
           '',
           '',
           '',
           ''),

    'OK': ('OK',
           'OK',
           'OK',
           '',
           '',
           '',
           '',
           '',
           '',
           ''),

    'cancel': ('Abbrechen',
               'Cancel',
               'Onderbreken',
           '',
           '',
           '',
           '',
           '',
           '',
           ''),

'aborted': ('Abgebrochen',
               'Aborted',
               'Onderbroken',
           '',
           '',
           '',
           '',
           '',
           '',
           ''),

    'delete': ('Löschen',
               'Delete',
               'Verwijder',
           '',
           '',
           '',
           '',
           '',
           '',
           ''),

    'delete_dx_history': ('DX-History Löschen',
                          'Delete DX-History',
                          'Verwijder DX-History',
           '',
           '',
           '',
           '',
           '',
           '',
           ''),

    'del_all': ('Alles Löschen',
                'Delete all',
                'Verwijder alles',
           '',
           '',
           '',
           '',
           '',
           '',
           ''),

    'go': ('Los',
           'Go',
           'Gaan',
           '',
           '',
           '',
           '',
           '',
           '',
           ''),

    'close': ('Schließen',
              'Close',
              'Sluiten',
           '',
           '',
           '',
           '',
           '',
           '',
           ''),

    'save': ('Speichern',
             'Save',
             'Opslaan',
           '',
           '',
           '',
           '',
           '',
           '',
           ''),

    'forward': ('Weiterleiten',
             'Forward',
             'Vooruit',
           '',
           '',
           '',
           '',
           '',
           '',
           ''),

    'answer': ('Antworten',
             'Answer',
             'Antwoord',
           '',
           '',
           '',
           '',
           '',
           '',
           ''),

    'send_file': ('Datei senden',
                  'Send File',
                  'Verstuur bestand',
           '',
           '',
           '',
           '',
           '',
           '',
           ''),

    'file_1': ('Datei',
               'File',
               'Bestand',
           '',
           '',
           '',
           '',
           '',
           '',
           ''),

    'file_2': ('Datei:',
               'File:',
               'Bestand:',
           '',
           '',
           '',
           '',
           '',
           '',
           ''),

    'locator_calc': ('Locator Rechner',
                     'Locator Calculator',
                     'Lokatie berekenen',
           '',
           '',
           '',
           '',
           '',
           '',
           ''),

    'aprs_mon': ('APRS-Server Monitor',
                 'APRS-Server Monitor',
                 'APRS-Server Monitor',
           '',
           '',
           '',
           '',
           '',
           '',
           ''),

    'protocol': ('Protokoll:',
                 'Protocol:',
                 'Protocol:',
           '',
           '',
           '',
           '',
           '',
           '',
           ''),

    'send_if_free': ('Senden wenn Band frei für (sek.):',
                     'Send when band is free for (sec.):',
                     'Zenden wanneer band vrij is',
           '',
           '',
           '',
           '',
           '',
           '',
           ''),

    'size': ('Größe:',
             'Size:',
             'Groot:',
           '',
           '',
           '',
           '',
           '',
           '',
           ''),

    'new': ('Neu',
            'New',
            'Nieuw',
           '',
           '',
           '',
           '',
           '',
           '',
           ''),

    'new_port': ('Neuer Port',
                 'New port',
                 'Nieuwe Poort',
           '',
           '',
           '',
           '',
           '',
           '',
           ''),

    'new_conn': ('Neu Verbindung',
                 'New Connection',
                 'Nieuwe verbinding',
           '',
           '',
           '',
           '',
           '',
           '',
           ''),

    'disconnect': ('Disconnecten',
                   'Disconnect',
                   'Verbreken',
           '',
           '',
           '',
           '',
           '',
           '',
           ''),

    'disconnect_all': ('ALLE disconnecten',
                       'Disconnect ALL',
                       'Verbreek alles',
           '',
           '',
           '',
           '',
           '',
           '',
           ''),

    'disconnect_all_ask': ('Wirklich ALLE Stationen disconnecten ?',
                           'Do you want to disconnect ALL stations?',
                           'Wilt u ALLE stations verbreken?',
           '',
           '',
           '',
           '',
           '',
           '',
           ''),

    'wx_window': ('Wetterstationen',
                  'Weather Stations',
                  'Weerstations',
           '',
           '',
           '',
           '',
           '',
           '',
           ''),

    'quit': ('Quit',
             'Quit',
             'sluiten',
           '',
           '',
           '',
           '',
           '',
           '',
           ''),

    'connections': ('Verbindungen',
                    'Connections',
                    'Koppelingen',
           '',
           '',
           '',
           '',
           '',
           '',
           ''),

    'copy': ('Kopieren',
             'Copy',
             'Kopiëren',
           '',
           '',
           '',
           '',
           '',
           '',
           ''),

    'past': ('Einfügen',
             'Past',
             'Invoegen',
           '',
           '',
           '',
           '',
           '',
           '',
           ''),

    'past_f_file': ('Aus Datei einfügen',
                    'Past from File',
                    'invoegen uit bestand',
           '',
           '',
           '',
           '',
           '',
           '',
           ''),

    'save_to_file': ('In Datei speichern',
                     'Save to File',
                     'Bestand opslaan',
           '',
           '',
           '',
           '',
           '',
           '',
           ''),

    'past_qso_f_file': ('Aus Datei einfügen',
                        'Past from File',
                        'Invoegen uit bestand',
           '',
           '',
           '',
           '',
           '',
           '',
           ''),

    'save_qso_to_file': ('QSO in Datei speichern',
                         'Save QSO to File',
                         'QSO opslaan',
           '',
           '',
           '',
           '',
           '',
           '',
           ''),

    'save_mon_to_file': ('Monitor in Datei speichern',
                         'Save Monitor to File',
                         'Kopieer monitor naar bestand',
           '',
           '',
           '',
           '',
           '',
           '',
           ''),

    'clean_qso_win': ('QSO/Vorschreibfenster löschen',
                      'Clear QSO/Prescription window',
                      'QSO verwijderen',
           '',
           '',
           '',
           '',
           '',
           '',
           ''),

    'clean_all_qso_win': ('Alle QSO/Vorschreibfenster löschen',
                          'Clear all QSO/Prescription window',
                          'Alle QSO verwijderen',
           '',
           '',
           '',
           '',
           '',
           '',
           ''),

    'clean_mon_win': ('Monitor löschen',
                      'Clear Monitor',
                      'Monitor wissen',
           '',
           '',
           '',
           '',
           '',
           '',
           ''),

    'edit': ('Bearbeiten',
             'Edit',
             'Bewerken',
           '',
           '',
           '',
           '',
           '',
           '',
           ''),

    'statistic': ('Statistik',
                  'Statistics',
                  'Statistieken',
           '',
           '',
           '',
           '',
           '',
           '',
           ''),

    'linkholder': ('Linkhalter',
                   'Link holder',
                   'Link houder',
           '',
           '',
           '',
           '',
           '',
           '',
           ''), #
    'clean_qso': ('QSO löschen',
                   'delete QSO',
                   'QSO verwijderen',
           '',
           '',
           '',
           '',
           '',
           '',
           ''),

    'tools': ('Tools',
              'Tools',
              'Hulpmiddelen',
           '',
           '',
           '',
           '',
           '',
           '',
           ''),

    'station': ('Station',
                'Station',
                'Station',
           '',
           '',
           '',
           '',
           '',
           '',
           ''),

    'stations': ('Stationen',
                 'Stations',
                 'Stations',
           '',
           '',
           '',
           '',
           '',
           '',
           ''),

    'port': ('Port',
             'Port',
             'Poort',
           '',
           '',
           '',
           '',
           '',
           '',
           ''),

    'channel': ('Kanal',
                'Channel',
                'Kanaal',
           '',
           '',
           '',
           '',
           '',
           '',
           ''),

    'beacon': ('Baken',
               'Beacons',
               'Baken',
           '',
           '',
           '',
           '',
           '',
           '',
           ''),

    'sprech': ('Sprachausgabe',
               'Speech output',
               'Spraakuitvoer',
           '',
           '',
           '',
           '',
           '',
           '',
           ''),

    'settings': ('Einstellungen',
                 'Settings',
                 'Instellingen',
           '',
           '',
           '',
           '',
           '',
           '',
           ''),

    'main_page': ('Hauptseite',
                  'Main Page',
                  'Hoofdpagina',
           '',
           '',
           '',
           '',
           '',
           '',
           ''),

    'passwords': ('Passwörter',
                  'Passwords',
                  'Wachtwoord',
           '',
           '',
           '',
           '',
           '',
           '',
           ''),

    'syspassword': ('Sys-Passwort:',
                    'Sys-Password:',
                    'Gebruiker-wachtwoord:',
           '',
           '',
           '',
           '',
           '',
           '',
           ''),

    'trys': ('Fake-Versuche:',
             'Fake-Attempts:',
             'Valse pogingen:',
           '',
           '',
           '',
           '',
           '',
           '',
           ''),

    'fillchars': ('Antwortlänge:',
                  'Response length:',
                  'Reactie lengte:',
           '',
           '',
           '',
           '',
           '',
           '',
           ''),

    'priv': ('Login',
             'Login',
             'Inlog',
           '',
           '',
           '',
           '',
           '',
           '',
           ''),

    'login_cmd': ('Login Kommando:',
                  'Login Command:',
                  'Inlog commando:',
           '',
           '',
           '',
           '',
           '',
           '',
           ''),

    'keybind': ('Tastaturbelegung',
                'Keyboard layout',
                'Toetsenbordindeling',
           '',
           '',
           '',
           '',
           '',
           '',
           ''),

    'about': ('Über',
              'About',
              'Over',
           '',
           '',
           '',
           '',
           '',
           '',
           ''),

    'help': ('Hilfe',
             'Help',
             'Hulp',
           '',
           '',
           '',
           '',
           '',
           '',
           ''),

    'number': ('Anzahl',
               'Number',
               'Nummer',
           '',
           '',
           '',
           '',
           '',
           '',
           ''),

    'minutes': ('Minuten',
                'Minutes',
                'Minuut',
           '',
           '',
           '',
           '',
           '',
           '',
           ''),

    'hours': ('Stunden',
              'Hours',
              'Uur',
           '',
           '',
           '',
           '',
           '',
           '',
           ''),

    'day': ('Tag',
            'Day',
            'Dag',
           '',
           '',
           '',
           '',
           '',
           '',
           ''),

    'month': ('Monat',
              'Month',
              'Maand',
           '',
           '',
           '',
           '',
           '',
           '',
           ''),

    'occup': ('Auslastung in %',
              'Occupancy in %',
              'Werkdruk in %',
           '',
           '',
           '',
           '',
           '',
           '',
           ''),

    'call': ('Call',
             'Call',
             'Gebruiker',
           '',
           '',
           '',
           '',
           '',
           '',
           ''),

    'name': ('Name',
             'Name',
             'Naam',
           '',
           '',
           '',
           '',
           '',
           '',
           ''),

    'fwd_list': ('Forward Warteschlange',
                 'Forward queue',
                 'Voorwaartse wachtrij',
           '',
           '',
           '',
           '',
           '',
           '',
           ''),

    'fwd_path': ('Forward Routen',
                 'Forward routes',
                 'Voorwaartse routes',
           '',
           '',
           '',
           '',
           '',
           '',
           ''),

    'start_fwd': ('FWD Start',
                  'FWD start',
                  'Start FWD',
           '',
           '',
           '',
           '',
           '',
           '',
           ''),

    'start_auto_fwd': ('AutoFWD Start',
                       'AutoFWD start',
                       'Start AutoFWD',
           '',
           '',
           '',
           '',
           '',
           '',
           ''),

    'msg_center': ('Nachrichten Center',
                   'Message Center',
                   'Berichten Center',
           '',
           '',
           '',
           '',
           '',
           '',
           ''),

    'qso_win_color': ('QSO Fenster Farben',
                      'QSO Win Color',
                      'QSO Win Kleur',
           '',
           '',
           '',
           '',
           '',
           '',
           ''),

    'text_color': ('Text Farben',
                   'Text Color',
                   'Text kleur',
           '',
           '',
           '',
           '',
           '',
           '',
           ''),

    'bg_color': ('Hintergrund Farben',
                 'Backgrund Color',
                 'BG kleur',
           '',
           '',
           '',
           '',
           '',
           '',
           ''),

    'mon_color': ('Monitor Farben',
                  'Monitor Colors',
                  'Monitor Kleur',
           '',
           '',
           '',
           '',
           '',
           '',
           ''),

    'c_text': ('C Text',
               'C Text',
               'C-Text',
           '',
           '',
           '',
           '',
           '',
           '',
           ''),

    'q_text': ('Quit Text',
               'Quit Text',
               'Quit-Text',
           '',
           '',
           '',
           '',
           '',
           '',
           ''),

    'i_text': ('Info Text',
               'Info Text',
               'Info-Text',
           '',
           '',
           '',
           '',
           '',
           '',
           ''),

    'li_text': ('Lang-Info Text',
                'Long-Info Text',
                'Lange-Info Text',
           '',
           '',
           '',
           '',
           '',
           '',
           ''),

    'news_text': ('News Text',
                  'News Text',
                  'Nieuws-Text',
           '',
           '',
           '',
           '',
           '',
           '',
           ''),

    'aprs_settings': ('APRS-Einstellungen',
                      'APRS-Settings',
                      'APRS-instellingen',
           '',
           '',
           '',
           '',
           '',
           '',
           ''),

    'aprs_pn_msg': ('APRS Private Nachrichten',
                    'APRS Private Messages',
                    'APRS Prive berichten',
           '',
           '',
           '',
           '',
           '',
           '',
           ''),

    'pn_msg': ('Private Nachrichten',
               'Private Messages',
               'Prive berichten',
           '',
           '',
           '',
           '',
           '',
           '',
           ''),

    'msg': ('Nachricht',
            'Message',
            'Bericht',
           '',
           '',
           '',
           '',
           '',
           '',
           ''),

    'new_msg': ('Neue Nachricht',
                'New Message',
                'Nieuw bericht',
           '',
           '',
           '',
           '',
           '',
           '',
           ''),

    'new_pr_mail': ('Neue PR-Mail',
                    'New PR-Mail',
                    'Nieuwe PR-Mail',
           '',
           '',
           '',
           '',
           '',
           '',
           ''),

    'send_all_now': ('Alles sofort senden',
                    'Send everything now',
                    'Stuur alles onmiddellijk',
           '',
           '',
           '',
           '',
           '',
           '',
           ''),

    'mark_all_read': ('Alle als gelesen markieren',
                    'Mark all as read',
                    'Markeer alles als gelezen',
           '',
           '',
           '',
           '',
           '',
           '',
           ''),

    'stat_settings': ('Station',
                      'Station',
                      'Gebruiker',
           '',
           '',
           '',
           '',
           '',
           '',
           ''), #

    'general_settings': ('Allgemein',
                      'General',
                      'Algemeen',
           '',
           '',
           '',
           '',
           '',
           '',
           ''),

    'new_stat': ('Neue Station',
                 'New Station',
                 'nieuwe gebruiker',
           '',
           '',
           '',
           '',
           '',
           '',
           ''),

    'txt_decoding': ('Umlautumwandlung',
                     'Text decoding',
                     'Text decoding',
           '',
           '',
           '',
           '',
           '',
           '',
           ''),

    'suc_save': ('Info: Station Einstellungen erfolgreich gespeichert.',
                 'Info: Station setiings saved.'
                 'Info: Gebruiker instellingen goed opgelsagen.',
           '',
           '',
           '',
           '',
           '',
           '',
           ''),

    'lob1': ('Lob: Das hast du sehr gut gemacht !!',
             'Praise: You did very well!!',
             'Dat heb je zeer goed gemaakt',
           '',
           '',
           '',
           '',
           '',
           '',
           ''),

    'lob2': ('Lob: Das hast du gut gemacht !!',
             'Praise: You did well!!',
             'Dat heb je goed gemaakt ',
           '',
           '',
           '',
           '',
           '',
           '',
           ''),

    'lob3': ('Lob: Das war eine gute Entscheidung. Mach weiter so. Das hast du gut gemacht.',
             'Praise: That was a good decision. Keep it up. You did well.',
             'Dat was een goede beslissing. Ga zo door. Dat heb je goed gemaakt.',
           '',
           '',
           '',
           '',
           '',
           '',
           ''), #

    'lob4': ('Lob: Du hast dir heute noch kein Lob verdient.',
             "Praise: You haven't earned any praise today.",
             'Je hebt vandaag geen lof verdiend.',
           '',
           '',
           '',
           '',
           '',
           '',
           ''),

    'lob5': ('Es tut mir leid, Dave. Ich fürchte, das kann ich nicht.',
             "I'm sorry, Dave. I'm afraid I can't do that.",
             'Het spijt me, Dave. Ik ben bang dat ik dat niet kan.',
           '',
           '',
           '',
           '',
           '',
           '',
           ''),

    'hin1': ('Hinweis: Der OK Button funktioniert noch !!',
             'Note: The OK button still works !!',
             'De OK knop werkt nog !!',
           '',
           '',
           '',
           '',
           '',
           '',
           ''),

    'hin2': ('Hinweis: Knack!! Abgebrochen..',
             'Note: Canceled !!',
             'geannuleerd!',
           '',
           '',
           '',
           '',
           '',
           '',
           ''),

    'date_time': ('Datum/Zeit',
             'Date/Time',
             'Datum/tijd',
             '',
             '',
             '',
             '',
             '',
             '',
             ''),

    'date': ('Datum',
             'Date',
             'Datum',
             '',
             '',
             '',
             '',
             '',
             '',
             ''),

    'message': ('Nachricht',
             'Message',
             'Nieuws',
             '',
             '',
             '',
             '',
             '',
             '',
             ''),

    'titel': ('Titel',
                'Title',
                'Titel',
                '',
                '',
                '',
                '',
                '',
                '',
                ''),

    'from': ('Von',
             'From',
             'van ',
           '',
           '',
           '',
           '',
           '',
           '',
           ''),

    'to': ('An',
           'To',
           'Naar ',
           '',
           '',
           '',
           '',
           '',
           '',
           ''),

    'subject': ('Betreff',
           'Subject',
           'Onderwerp ',
           '',
           '',
           '',
           '',
           '',
           '',
           ''),

    'versatz': ('Versatz',
                'Offset',
                'Verzet',
           '',
           '',
           '',
           '',
           '',
           '',
           ''),

    'intervall': ('Intervall',
                  'Interval',
                  'Interval',
           '',
           '',
           '',
           '',
           '',
           '',
           ''),

    'active': ('Aktiviert',
               'Activated',
               'Ingeschakeld',
           '',
           '',
           '',
           '',
           '',
           '',
           ''),

    'text_fm_file': ('Text aus Datei',
                     'Text from File',
                     'Tekst uit bestand ',
           '',
           '',
           '',
           '',
           '',
           '',
           ''),

    'beacon_settings': ('Baken',
                        'Beacon',
                        'Baken',
           '',
           '',
           '',
           '',
           '',
           '',
           ''),

    'pipetool_settings': ('Pipe-Tool Einstellungen',
                          'Pipe-Tool Settings',
                          'Pipe-Tool Instellingen',
           '',
           '',
           '',
           '',
           '',
           '',
           ''),

    'new_pipe': ('Neue Pipe',
                 'New Pipe',
                 'Nieuwe Pipe',
           '',
           '',
           '',
           '',
           '',
           '',
           ''),

    'new_pipe_fm_connection': ('Pipe auf Verbindung',
                               'Pipe on Connection',
                               'Pipe op aansluiting',
           '',
           '',
           '',
           '',
           '',
           '',
           ''),

    'tx_file': ('TX Datei',
                'TX File',
                'TX-File',
           '',
           '',
           '',
           '',
           '',
           '',
           ''),

    'rx_file': ('RX Datei',
                'RX File',
                'RX-File',
           '',
           '',
           '',
           '',
           '',
           '',
           ''),

    'port_cfg_std_parm': ('Standard Parameter. Werden genutzt wenn nirgendwo anders (Station/Client) definiert.',
                          'Default parameters. Are used if not defined anywhere else (station/client).',
                          'Standaardparameters. Worden gebruikt als ze nergens anders zijn gedefinieerd (station/client).',
           '',
           '',
           '',
           '',
           '',
           '',
           ''),

    'port_cfg_psd_txd': ('Pseudo TX-Delay (Wartezeit zwischen TX und RX). Wird nicht als KISS Parameter am TNC gesetzt.',
                         'Pseudo TX delay (waiting time between TX and RX). Is not set as a KISS parameter on the TNC.',
                         'Pseudo TX-vertraging (wachttijd tussen TX en RX). Is op de TNC niet als KISS-parameter ingesteld.',
           '',
           '',
           '',
           '',
           '',
           '',
           ''),

    'port_cfg_pac_len': ('Paket Länge. 1 - 256',
                         'Packet length. 1-256',
                         'Pakket lengte. 1-256',
           '',
           '',
           '',
           '',
           '',
           '',
           ''),

    'port_cfg_pac_max': ('Max Paket Anzahl. 1 - 7',
                         'Max Packets. 1 - 7',
                         'Max pakketnummer. 1 - 7',
           '',
           '',
           '',
           '',
           '',
           '',
           ''),

    'port_cfg_port_name': ('Port Bezeichnung für MH und Monitor( Max: 4 ):',
                           'Port designation for MH and monitor (Max: 4):',
                           'Poortaanduiding voor MH en monitor (Max: 4):',
           '',
           '',
           '',
           '',
           '',
           '',
           ''),

    'port_cfg_not_init': ('!! Port ist nicht Initialisiert !!',
                          '!! Port is not initialized!!',
                          '!! Poort is niet geïnitialiseerd!!',
           '',
           '',
           '',
           '',
           '',
           '',
           ''),

    'new_beacon': ('Neue Bake',
                   'New Beacon',
                   'Nieuw baken',
           '',
           '',
           '',
           '',
           '',
           '',
           ''),

    'last_packet': ('letztes Paket',
                    'last packet',
                    'laatste pakket',
           '',
           '',
           '',
           '',
           '',
           '',
           ''),

    'scrolling': ('Auto Scrollen',
                  'Auto scrolling',
                  'Automatisch scrollen',
           '',
           '',
           '',
           '',
           '',
           '',
           ''),

    'msg_box_mh_delete': ('MH-Liste Löschen',
                          'Delete MH list',
                          'Verwijder MH-lijst',
           '',
           '',
           '',
           '',
           '',
           '',
           ''),

    'msg_box_mh_delete_msg': ('Komplette MH-Liste löschen?',
                              'Delete entire MH list?',
                            'Volledige MH-lijst verwijderen?',
           '',
           '',
           '',
           '',
           '',
           '',
           ''),

    'msg_box_delete_data': ('Daten Löschen',
                            'Delete data',
                            'Verwijder data',
           '',
           '',
           '',
           '',
           '',
           '',
           ''),

    'msg_box_delete_data_msg': ('Alle Daten löschen?',
                                'Delete all data?',
                                'Alle gegevens verwijderen?',
           '',
           '',
           '',
           '',
           '',
           '',
           ''),

    'data': ('Daten',
             'Data',
             'Gegevens',
           '',
           '',
           '',
           '',
           '',
           '',
           ''),

    'multicast_warning': (
        'Vorsicht bei Nodenanbindungen wie TNN. Verlinkungen mehrerer Noden via Multicast kann zu Problemen führen!',
        'Be careful with node connections like TNN. Linking multiple nodes via multicast can lead to problems!',
        'Voorzichtigmet nodeverbinding zoals TNN, verbinden meervoudige nodes via multicast kan leiden naar problemen!',
           '',
           '',
           '',
           '',
           '',
           '',
           ''),

    'user_db': (
        'User Datenbank',
        'User Database',
        'Gebruikersdatabase',
           '',
           '',
           '',
           '',
           '',
           '',
           ''),

    # CLI
    'cmd_help_bell': ('Sysop Rufen',
                      'Call Sysop',
                      'Gebruiker roepen',
           '',
           '',
           '',
           '',
           '',
           '',
           ''),

    'cmd_help_wx': ('Wetterstationen',
                    'Weather stations',
                    'Weerstations',
           '',
           '',
           '',
           '',
           '',
           '',
           ''),

    'cmd_help_user_db': ('Call DB Abfrage',
                         'Get Call DB entry',
                         'Ontvang gebruiker DB-invoer',
           '',
           '',
           '',
           '',
           '',
           '',
           ''),

    'cmd_help_set_name': ('Namen eintragen',
                          'Enter Name',
                          'naam ingevuld',
           '',
           '',
           '',
           '',
           '',
           '',
           ''),

    'cmd_help_set_qth': ('QTH eintragen',
                         'Enter QTH',
                         'Locatie ingevuld',
           '',
           '',
           '',
           '',
           '',
           '',
           ''),

    'cmd_help_set_loc': ('Locator eintragen',
                         'Enter Locator',
                         'Locator ingevuld',
           '',
           '',
           '',
           '',
           '',
           '',
           ''),

    'cmd_help_set_zip': ('Postleitzahl eintragen',
                         'Enter ZIP',
                         'Postcode ingevuld',
           '',
           '',
           '',
           '',
           '',
           '',
           ''),

    'cmd_help_set_prmail': ('PR-MAIL Adresse eintragen',
                            'Enter PR-MAIL Address',
                            'PR-MAIL ingevuld',
           '',
           '',
           '',
           '',
           '',
           '',
           ''),

    'cmd_help_set_email': ('E-MAIL Adresse eintragen',
                           'Enter E-MAIL Address',
                           'E-MAIL ingevuld',
           '',
           '',
           '',
           '',
           '',
           '',
           ''),

    'cmd_help_set_http': ('HTTP eintragen',
                          'Enter HTTP',
                          'HTTP ingevuld',
           '',
           '',
           '',
           '',
           '',
           '',
           ''),

    'cli_no_user_db_ent': (' # Eintag nicht in Benutzer Datenbank vorhanden!',
                           ' # Entry not in user database!',
                           ' # Invoer niet in gebruikersdatabase!',
           '',
           '',
           '',
           '',
           '',
           '',
           ''),

    'cli_name_set': (' # Name eingetragen',
                     ' # Username is set',
                     ' # Naam ingevoerd',
           '',
           '',
           '',
           '',
           '',
           '',
           ''),

    'cli_qth_set': (' # QTH eingetragen',
                    ' # QTH is set',
                    ' # Locatie ingevoerd',
           '',
           '',
           '',
           '',
           '',
           '',
           ''),

    'cli_loc_set': (' # Locator eingetragen',
                    ' # Locator is set',
                    ' # Locator ingevoerd',
           '',
           '',
           '',
           '',
           '',
           '',
           ''),

    'cli_zip_set': (' # Postleitzahl eingetragen',
                    ' # ZIP is set',
                    ' # Postcode ingevoerd',
           '',
           '',
           '',
           '',
           '',
           '',
           ''),

    'cli_prmail_set': (' # PR-Mail Adresse eingetragen',
                       ' # PR-Mail Address is set',
                       ' # PR-Mail ingevoerd',
           '',
           '',
           '',
           '',
           '',
           '',
           ''),

    'cli_email_set': (' # E-Mail Adresse eingetragen',
                      ' # E-Mail Address is set',
                      ' # E-Mail ingevoerd',
           '',
           '',
           '',
           '',
           '',
           '',
           ''),

    'cli_http_set': (' # HTTP eingetragen',
                     ' # HTTP is set',
                     ' # HTTP ingevoerd',
           '',
           '',
           '',
           '',
           '',
           '',
           ''),

    'cli_text_encoding_no_param': (' # Bitte ein ä senden. Bsp.: UM ä.\r # Derzeitige Einstellung:',
                                   ' # Please send an ä. Example: UM ä.\r # Current setting:',
                                   ' # Stuur een  ä. voorbeeld ä.\r # Huidige instelling:',
           '',
           '',
           '',
           '',
           '',
           '',
           ''),

    'cli_text_encoding_error_not_found': (' # Umlaute wurden nicht erkannt !',
                                          " # Couldn't detect right text encoding",
                                          ' # Kan de juiste tekstcodering niet detecteren',
           '',
           '',
           '',
           '',
           '',
           '',
           ''),

    'cli_text_encoding_set': (' # Umlaute/Text de/enkodierung erkannt und gesetzt auf:',
                              " # Text de/encoding detected and set to:",
                              ' # Tekstde/codering gedetecteerd en ingesteld op:',
           '',
           '',
           '',
           '',
           '',
           '',
           ''),

    'port_overview': ('Port Übersicht',
                      'Port Overview',
                      'Poort overzicht',
           '',
           '',
           '',
           '',
           '',
           '',
           ''),

    'cmd_shelp': ('Kurzhilfe',
                  'Short help',
                  'Korte hulp',
           '',
           '',
           '',
           '',
           '',
           '',
           ''),

    'time_connected': ('Connect Dauer',
                       'Connect duration',
                       'verbindingsduur',
           '',
           '',
           '',
           '',
           '',
           '',
           ''),

    'cmd_not_known': ('Dieses Kommando ist dem System nicht bekannt !',
                      'The system does not know this command !',
                      'Het systeem kent deze opdracht niet !',
           '',
           '',
           '',
           '',
           '',
           '',
           ''),

    'auto_text_encoding': ('Automatisch Umlaut Erkennung. ä als Parameter. > UM ä',
                           'Automatic detection of text encoding. ä as a parameter. > UM ä',
                           'Automatische detectie van tekstcodering. ä als parameter. > UM ä',
           '',
           '',
           '',
           '',
           '',
           '',
           ''),

    'cmd_help_lcstatus': ('Verbundene Terminalkanäle anzeigen (ausführliche Version)',
                          'Show connected terminal channels (detailed version)',
                          'Toon aangesloten terminalkanalen (gedetailleerde versie)',
           '',
           '',
           '',
           '',
           '',
           '',
           ''),

    'cli_no_wx_data': ('Keine Wetterdaten vorhanden.',
                       'No WX data available',
                       'Geen WX beschikbaar.',
           '',
           '',
           '',
           '',
           '',
           '',
           ''),

    'cli_no_data': ('Keine Daten vorhanden.',
                    'No data available.',
                    'Geen gegevens beschikbaar.',
           '',
           '',
           '',
           '',
           '',
           '',
           ''),

    'cli_no_tracer_data': (
        'Keine Tracerdaten vorhanden.',
        'No Tracer data available',
        'Geen tracergegevens beschikbaar.',
           '',
           '',
           '',
           '',
           '',
           '',
           ''),

    'cli_change_language': ('Sprache ändern.',
                            'Change language.',
                            'Taal veranderen',
           '',
           '',
           '',
           '',
           '',
           '',
           ''),

    'cli_lang_set': ('Sprache auf Deutsch geändert.',
                     'Language changed to English.',
                     'Taal veranderd naar Nederlands.',
           '',
           '',
           '',
           '',
           '',
           '',
           ''),

    'cli_no_lang_param': ('Sprache nicht erkannt! Mögliche Sprachen: ',
                          'Language not recognized! Possible languages: ',
                          'Taal niet herkend! Mogelijke talen: ',
           '',
           '',
           '',
           '',
           '',
           '',
           ''),

    'cmd_bell': ('Sysop wird gerufen !!',
                 'Sysop is called!!',
                 'Gebruiker wordt geroepen!!',
           '',
           '',
           '',
           '',
           '',
           '',
           ''),

    'cmd_bell_again': ('Sysop wurde bereits gerufen..',
                       'Sysop has already been called..',
                       'Gebruiker is al geroepen..',
           '',
           '',
           '',
           '',
           '',
           '',
           ''),

    'cmd_bell_gui_msg': ('verlangt nach dem Sysop !!',
                         'asks for the sysop!!',
                         'vraagt om de gebruiker!!',
           '',
           '',
           '',
           '',
           '',
           '',
           ''),

    'cmd_c_noCall': ('# Bitte Call eingeben..',
                     '# Please enter call..',
                     '# Voer een oproep in..',
           '',
           '',
           '',
           '',
           '',
           '',
           ''),

    'cmd_c_badCall': ('# Ungültiger Ziel Call..',
                     '# Invalid destination call..',
                     '# Ongeldige bestemmingsoproep..',
           '',
           '',
           '',
           '',
           '',
           '',
           ''),
    'cmd_c_badPort': ('# Ungültige Port Angabe..',
                     '# Invalid port specification..',
                     '# Ongeldige poortspecificatie..',
           '',
           '',
           '',
           '',
           '',
           '',
           ''),

    'cmd_c_noPort': ('# Ungültiger Port..',
                     '# Invalid port..',
                     '# Ongeldige poort..',
           '',
           '',
           '',
           '',
           '',
           '',
           ''),

    #####################################################
    # MCast

    'cmd_help_mcast_move_ch': ('MCast Kanal wechseln',
                               'Change MCast channel',
                               'MCast kanaal wijzigen',
                               '',
                               '',
                               '',
                               '',
                               '',
                               '',
                               ''),

    'cmd_help_mcast_ch_info': ('MCast Kanal Info',
                               'MCast channel info',
                               'MCast kanaalinformatie',
                               '',
                               '',
                               '',
                               '',
                               '',
                               '',
                               ''),

    'cmd_help_mcast_channels': ('MCast Kanal Übersicht',
                               'MCast channel overview',
                               'MCast kanaaloverzicht',
                               '',
                               '',
                               '',
                               '',
                               '',
                               '',
                               ''), #

    'cmd_help_mcast_set_axip': ('Eigene AXIP Adresse eintragen / anzeigen lassen',
                                'Enter/display your own AXIP address',
                                'Voer/toon uw eigen AXIP-adres in',
                                '',
                                '',
                                '',
                                '',
                                '',
                                '',
                                ''),

    'mcast_new_user_beacon': (
        # Not longer than 73 Chars (Text + Call-SSID = max. 80 Chars)
         '-= Willkommen auf dem AXIP-MCast Server. Registriere dich auf {} =-',
         '-= Welcome to the AXIP-MCast Server. Please connect {} to register =-',
         '-= Welcome to the AXIP-MCast Server. Please connect {} to register =-',
         '',
         '',
         '',
         '',
         '',
         '',
         ''),

    'mcast_new_user_reg_beacon': (
        # Not longer than 73 Chars (Text + Call-SSID = max. 80 Chars) per Line
        # Max 256
        ('-= Du wurdest erfolgreich auf dem MCast-Server registriert =-\r'
         '-= Du befindest dich auf Kanal {} ({}) =-'),
        ('-= You have been successfully registered on the MCast server =-\r'
         '-= You are on channel {} ({}) =-'),
        ('-= U bent succesvol geregistreerd op de MCast-server. =-\r'
         '-= Je bevindt je op kanaal {} ({}) =-'),
        ('\r'
         ''),
        ('\r'
         ''),
        ('\r'
         ''),
        ('\r'
         ''),
        ('\r'
         ''),
        ('\r'
         ''),
         ''),

    'mcast_user_enters_channel_beacon': (
        # Not longer than 73 Chars (Text + Call-SSID = max. 80 Chars)
         '-= {} hat den Kanal betreten =-',
         '-= {} has entered the channel =-',
         '-= {} is het kanaal binnengekomen =-',
         '',
         '',
         '',
         '',
         '',
         '',
         ''),

    'mcast_user_left_channel_beacon': (
        # Not longer than 73 Chars (Text + Call-SSID = max. 80 Chars)
         '-= {} hat den Kanal verlassen =-',
         '-= {} has left the channel =-',
         '-= {} het kanaal verlaten =-',
         '',
         '',
         '',
         '',
         '',
         '',
         ''),

    #####################################################
    # BOX CLI
    'cmd_r': (
        # Not longer than 73 Chars (Text + Call-SSID = max. 80 Chars)
         '<MSG#> Liest die Nachricht mit der entspr. Nummer aus.',
         '<MSG#> Reads the message with the corresponding number.',
         '<MSG#> Leest het bericht met het bijbehorende nummer.',
         '',
         '',
         '',
         '',
         '',
         '',
         ''),

    'cmd_sp': (
        # Not longer than 73 Chars (Text + Call-SSID = max. 80 Chars)
        'SP <Call> @ <BBS> : Sendet eine persoenliche Nachricht an Rufzeichen',
        'SP <Call> @ <BBS> : Sends a personal message to call sign',
        'SP <Call> @ <BBS>: Stuurt een persoonlijk bericht naar roepnamen',
        '',
        '',
        '',
        '',
        '',
        '',
        ''),

    'cmd_sb': (
        # Not longer than 73 Chars (Text + Call-SSID = max. 80 Chars)
        ('SB <Rubrik> @ <Verteiler> Sendet ein Bulletin in eine Rubrik \r'
        '              fuer mehrere Boxen in einer Region.'),
        ('SB <Category> @ <Distribution> Sends a bulletin to a category \r'
        '              for multiple boxes in a region.'),
        ('SB <categorie> @ <distributie> Stuurt een bulletin naar een categorie \r'
        '              voor meerdere dozen in een regio.'),
        '',
        '',
        '',
        '',
        '',
        '',
        ''),

    'cmd_ln': (
        # Not longer than 73 Chars (Text + Call-SSID = max. 80 Chars)
         'Listet alle eigenen neuen Nachrichten auf.',
         'Lists all of your own new messages.',
         'Geeft al uw eigen nieuwe berichten weer.',
         '',
         '',
         '',
         '',
         '',
         '',
         ''),

    'cmd_lm': (
        # Not longer than 73 Chars (Text + Call-SSID = max. 80 Chars)
         'Listet alle eigenen Nachrichten.',
         'Lists all of your own messages.',
         'Geeft al uw eigen berichten weer.',
         '',
         '',
         '',
         '',
         '',
         '',
         ''),

    'cmd_lb': (
        # Not longer than 73 Chars (Text + Call-SSID = max. 80 Chars)
         'Listet alle Bulletin Nachrichten.',
         'Lists all bulletin messages.',
         'Geeft een overzicht van alle bulletinberichten.',
         '',
         '',
         '',
         '',
         '',
         '',
         ''),

    'cmd_km': (
        # Not longer than 73 Chars (Text + Call-SSID = max. 80 Chars)
        'Loescht alle pers. Nachrichten, die man bereits gelesen hat.',
        'Deletes all personal messages that you have already read.',
        'Verwijdert alle persoonlijke berichten die u al hebt gelezen.',
        '',
        '',
        '',
        '',
        '',
        '',
        ''),

    'cmd_k': (
        # Not longer than 73 Chars (Text + Call-SSID = max. 80 Chars)
        '<MSG#> Loescht die Nachricht mit der entspr. Nummer.',
        '<MSG#> Deletes the message with the corresponding number.',
        '<MSG#> Verwijdert het bericht met het bijbehorende nummer.',
        '',
        '',
        '',
        '',
        '',
        '',
        ''),

    'cmd_op': (
        # Not longer than 73 Chars (Text + Call-SSID = max. 80 Chars)
         'Anzahl der Zeilen pro Seite. Nur OP aus.',
         'Number of lines per page. Just OP = off.',
         'Aantal regels per pagina. OP alleen = uit',
         '',
         '',
         '',
         '',
         '',
         '',
         ''),

    'op_prompt': (
        # Not longer than 73 Chars (Text + Call-SSID = max. 80 Chars)
         '\r # (A)=Abbruch, (R)=Lesen, (Return)=weiter -->',
         '\r # (A)=Cancel, (R)=Read, (Return)=continue -->',
         '\r # (A)=Annuleren, (R)=Lezen, (Terug)=doorgaan -->',
         '',
         '',
         '',
         '',
         '',
         '',
         ''),

    'box_new_mail_ctext': (
        # Not longer than 73 Chars (Text + Call-SSID = max. 80 Chars)
         '\r\r # BOX: Du hast {} neu Mails.\r\r',
         '\r\r # BOX : You have {} new mails.\r\r',
         '\r\r # BOX: Je hebt {} nieuwe mails.\r\r',
         '',
         '',
         '',
         '',
         '',
         '',
         ''),

    'box_cmd_op2': (
        # Not longer than 73 Chars (Text + Call-SSID = max. 80 Chars)
         '\r # OP: Fehler, ungültiger Parameter.\r',
         '\r # OP : Error, Invalid Parameter.\r',
         '\r # OP: Fout, ongeldige parameter.\r',
         '',
         '',
         '',
         '',
         '',
         '',
         ''),

    'box_cmd_op1': (
        # Not longer than 73 Chars (Text + Call-SSID = max. 80 Chars)
         '\r # OP : Kein Seitenstop.\r',
         '\r # OP : No side stop.\r',
         '\r # OP: Geen zijstop.\r',
         '',
         '',
         '',
         '',
         '',
         '',
         ''),

    'box_cmd_op3': (
        # Not longer than 73 Chars (Text + Call-SSID = max. 80 Chars)
         '\r # OP : Seitenstop auf {} Zeilen eingestellt.\r',
         '\r # OP : Page stop set to {} lines.\r',
         '\r # OP: Paginastop ingesteld op {} regels.\r',
         '',
         '',
         '',
         '',
         '',
         '',
         ''),

    'box_lm_header': (
        # Not longer than 73 Chars (Text + Call-SSID = max. 80 Chars)
         'Msg#  TSLD Byte   An    @ BBS   Von    Dat./Zeit Titel\r',
         'Msg#  TSLD Byte   To    @ BBS   From   Dat./Time Head\r',
         'Msg#  TSLD Byte   Naar  @ BBS   Van    Dat./Tijd Titel\r',
         '',
         '',
         '',
         '',
         '',
         '',
         ''),

    'box_r_no_msg_found': (
        # Not longer than 73 Chars (Text + Call-SSID = max. 80 Chars)
         '\r\r # Nachricht {} nicht gefunden ! \r\r',
         '\r\r # Message {} not found! \r\r',
         '\r\r # Bericht {} niet gevonden! \r\r',
         '',
         '',
         '',
         '',
         '',
         '',
         ''),

    'box_parameter_error': (
        # Not longer than 73 Chars (Text + Call-SSID = max. 80 Chars)
         '\r # Fehler, ungültiger Parameter.\r',
         '\r # Error, Invalid Parameter.\r',
         '\r # Fout, ongeldige parameter.\r',
         '',
         '',
         '',
         '',
         '',
         '',
         ''),

    'box_msg_error': (
        # Not longer than 73 Chars (Text + Call-SSID = max. 80 Chars)
         '\r # Interner Fehler, kann Nachricht nicht lesen.\r',
         '\r # Internal error, cannot read message.\r',
         '\r # Interne fout, kan bericht niet lezen.\r',
         '',
         '',
         '',
         '',
         '',
         '',
         ''),

    'box_msg_foter': (
        # Not longer than 73 Chars (Text + Call-SSID = max. 80 Chars)
         '\r\r--- Ende der Nachricht #{} an {} von {} BID:{} ---\r\r',
         '\r\r--- End of message #{} to {} from {} BID:{} ---\r\r',
         '\r\r--- Einde van bericht #{} tot {} van {} BID:{} ---\r\r',
         '',
         '',
         '',
         '',
         '',
         '',
         ''),

    'box_msg_del': (
        # Not longer than 73 Chars (Text + Call-SSID = max. 80 Chars)
        '\r # Es wurden {} Nachrichten gelöscht.\r',
        '\r # {} messages have been deleted.\r',
        '\r # {} berichten zijn verwijderd.\r',
        '',
        '',
        '',
        '',
        '',
        '',
        ''),

    'box_msg_del_k': (
        # Not longer than 73 Chars (Text + Call-SSID = max. 80 Chars)
        '\r # Nachrichte(n) {} wurde(n) gelöscht.\r',
        '\r # Message(s) {} have been deleted.\r',
        '\r # Berichte(n) {} zijn verwijderd.\r',
        '',
        '',
        '',
        '',
        '',
        '',
        ''),

    'box_error_no_address': (
        # Not longer than 73 Chars (Text + Call-SSID = max. 80 Chars)
        '\r # Kein Empfänger angegeben. SP XX0XX oder SP XX0XX@XBBS0\r',
        '\r # No recipient specified. SP XX0XX or SP XX0XX@XBBS0.\r',
        '\r # Geen ontvanger opgegeven. SP XX0XX of SP XX0XX@XBBS0.\r',
        '',
        '',
        '',
        '',
        '',
        '',
        ''),

    'box_error_invalid_dist': (
        # Not longer than 73 Chars (Text + Call-SSID = max. 80 Chars)
        '\r # Kein Verteiler in BBS-Adresse {}\r',
        '\r # No distribution list in BBS address {}\r',
        '\r # Geen distributeur in BBS-adres {}\r',
        '',
        '',
        '',
        '',
        '',
        '',
        ''),

    'box_cmd_sp_routing_to': (
        # Not longer than 73 Chars (Text + Call-SSID = max. 80 Chars)
        ('\r # Routing: {}\r'
         'Titel der Nachricht an {}:\r'),
        ('\r # Routing: {}\r'
         'Title of message to {}:\r'),
        ('\r # Routing: {}\r'
         'Berichttitel aan {}:\r'),
        '',
        '',
        '',
        '',
        '',
        '',
        ''),

    'box_cmd_sp_local': (
        # Not longer than 73 Chars (Text + Call-SSID = max. 80 Chars)
        ('\r # Lokale Nachricht.\r'
         'Titel der Nachricht an {}:\r'),
        ('\r # Local message.\r'
         'Title of message to {}:\r'),
        ('\r # Lokaal bericht.\r'
         'Berichttitel aan {}:\r'),
        '',
        '',
        '',
        '',
        '',
        '',
        ''),

    'box_cmd_sp_enter_msg': (
        # Not longer than 73 Chars (Text + Call-SSID = max. 80 Chars)
        'Text eingeben ... (Ende mit /EX oder Strg-Z):\r',
        'Enter text ... (End with /EX or Ctrl-Z):\r',
        'Tekst invoeren... (eindigen met /EX of Ctrl-Z):\r',
        '',
        '',
        '',
        '',
        '',
        '',
        ''),

    'box_cmd_sp_abort_msg': (
        # Not longer than 73 Chars (Text + Call-SSID = max. 80 Chars)
        '\r # Nachricht fuer {} anulliert\r',
        '\r # Message for {} canceled\r',
        '\r # Bericht voor {} geannuleerd\r',
        '',
        '',
        '',
        '',
        '',
        '',
        ''),

    'box_cmd_sp_msg_accepted': (
        # Not longer than 73 Chars (Text + Call-SSID = max. 80 Chars)
        ('\r # Ok. Nachricht an Adresse {} @ {} wird geforwardet.\r'
           '   via: {} MID: {} Bytes: {}\r\r'),
        ('\r # Ok. Bericht wordt doorgestuurd naar adres {} @ {}\r'
           '   via: {} MID: {} Bytes: {}\r\r'),
        ('\r # Ok. Message to address {} @ {} is being forwarded\r'
           '   via: {} Mid: {} Bytes: {}\r\r'),
        '',
        '',
        '',
        '',
        '',
        '',
        ''),

    'box_cmd_sp_msg_accepted_local': (
        # Not longer than 73 Chars (Text + Call-SSID = max. 80 Chars)
        ('\r # Ok. Nachricht an Adresse {} bleibt lokal.\r'
         '   MID: {} Bytes: {}\r\r'),
        ('\r # Ok. Message to address {} remains local.\r'
         '   MID: {} Bytes: {}\r\r'),
        ('\r# Oké. Bericht aan adres {} blijft lokaal.\r'
         '   Mid: {} Bytes: {}\r\r'),
        '',
        '',
        '',
        '',
        '',
        '',
        ''),

    #####################################################
    # BOX GUI
    'own_station': (
        # Not longer than 73 Chars (Text + Call-SSID = max. 80 Chars)
        'Eigene Station',
        'Own station',
        'Eigen station',
        '',
        '',
        '',
        '',
        '',
        '',
        ''),

    'region': (
        # Not longer than 73 Chars (Text + Call-SSID = max. 80 Chars)
        'Region',
        'Region',
        'Regio',
        '',
        '',
        '',
        '',
        '',
        '',
        ''),

    'fwd_settings': (
        'Forward',
        'Forward',
        'Forward',
        '',
        '',
        '',
        '',
        '',
        '',
        ''),

    'routing_settings': (
        'Routing',
        'Routing',
        'Routing',
        '',
        '',
        '',
        '',
        '',
        '',
        ''),

    'allowRevFWD': (
        'Erlaube Reverse-FWD',
        'Allow Reverse-FWD',
        'Sta Reverse-FWD toe',
        '',
        '',
        '',
        '',
        '',
        '',
        ''),

    'allowPN_AutoPath': (
        'Erlaube PN AutoPath',
        'Allow PN AutoPath',
        'PN AutoPath toestaan',
        '',
        '',
        '',
        '',
        '',
        '',
        ''),

    'allowPN_AlterPath': (
        'PN-Alternativroute zulassen',
        'Allow PN alternative route',
        'Alternatieve PN-route toestaan',
        '',
        '',
        '',
        '',
        '',
        '',
        ''),

    'allow_PN_FWD': (
        'Privat Mail FWD zulassen',
        'Allow private mail FWD',
        'Sta het doorsturen van privémail toe',
        '',
        '',
        '',
        '',
        '',
        '',
        ''),

    'allow_BL_FWD': (
        'Bulletin Mail FWD zulassen',
        'Allow Bulletin mail FWD',
        'Doorsturen van bulletinmail toestaan',
        '',
        '',
        '',
        '',
        '',
        '',
        ''),

    'fwd_autoPath_help': (
        ('0  = deaktiviert\n'
         '1  = am aktuellsten\n'
         '2  = am besten (geringe Sprünge)'),
        ('0 = disabled\n'
         '1 = most recent\n'
         '2 = best (lowes hops)'),
        ('0 = uitgeschakeld\n'
         '1 = meest recente\n'
         '2 = beste (kleine sprongen)'),
        '',
        '',
        '',
        '',
        '',
        '',
        ''),

    'bbs_sett_fwd_global': (
        'Forwarding Global',
        'Forwarding Global',
        'Forwarding globaal',
        '',
        '',
        '',
        '',
        '',
        '',
        ''),

    'bbs_sett_local_dist': (
        'Lokale Verteiler',
        'Local distributors',
        'Lokale distributeurs',
        '',
        '',
        '',
        '',
        '',
        '',
        ''),

    'bbs_sett_local_theme': (
        'Lokale Bulletin Themen',
        'Local Bulletin Themes',
        'Lokale Bulletin thema s',
        '',
        '',
        '',
        '',
        '',
        '',
        ''),

    'bbs_sett_block_bbs': (
        'BBS blockieren',
        'Block BBS',
        'BBS blokkeren',
        '',
        '',
        '',
        '',
        '',
        '',
        ''),

    'bbs_sett_block_call': (
        'CALL blockieren',
        'Block CALL',
        'CALL blokkeren',
        '',
        '',
        '',
        '',
        '',
        '',
        ''),

    'bbs_sett_pn_bbs_out': (
        'Privat Mail > ausgehend',
        'Private mail > outgoing',
        'Privémail > uitgaand',
        '',
        '',
        '',
        '',
        '',
        '',
        ''),

    'bbs_sett_pn_bbs_in': (
        'Privat Mail > eingehend',
        'Private mail > incoming',
        'Privémail > inkomend',
        '',
        '',
        '',
        '',
        '',
        '',
        ''),

    'bbs_sett_bl_bbs_in': (
        'Bulletin Mail > eingehend',
        'Bulletin mail > incoming',
        'Bulletin mail > inkomend',
        '',
        '',
        '',
        '',
        '',
        '',
        ''),

    'bbs_sett_bl_bbs_out': (
        'Bulletin Mail > ausgehend',
        'Bulletin mail > outgoing',
        'Bulletin mail > uitgaand',
        '',
        '',
        '',
        '',
        '',
        '',
        ''),

    'read_ed': (
        'gelesen',
        'read',
        'lezen',
        '',
        '',
        '',
        '',
        '',
        '',
        ''),

    'msgC_sendet_msg': (
        'Gesendet',
        'Sendet',
        'Verstuurd',
        '',
        '',
        '',
        '',
        '',
        '',
        ''),

    'saved': (
        'Gespeichert',
        'Saved',
        'Opgeslagen',
        '',
        '',
        '',
        '',
        '',
        '',
        ''),

    'private': (
        'Privat',
        'Private',
        'Privé',
        '',
        '',
        '',
        '',
        '',
        '',
        ''),

}