# Translated by Santi EA2SPS(HAM)
#
#
# SP = Index 10

STR_TABLE_SP = {
    'default_ctext':                "\n-= Hola $destName, =-\n-= Bienvenido a $ownCall ($distance km), =-\n-= al Canal-Terminal $channel <> Puerto $portNr. =-\n-= Está es tu conexión Num. $connNr. =-\n-= $ver - Max-Frame: $parmMaxFrame - Pac-Len: $parmPacLen =-\n\n # Último loggin : $lastConnDate um: $lastConnTime\n\n",
    'default_btext':                '\n73 de $ownCall ...\n',
    'bbs_new_user_reg0':            'Usar esta BBS como su BBS domestica? S/N> ',
    'bbs_new_user_reg_confirm':     'Pulsa <Enter> para confirmar o reentrar al cambio.\r>',
    'bbs_new_user_reg1':            "\rEsta es la primera conexión a este sistema.\rBefore we continue, please answer the questions. THANK YOU!\rTip: You don't have to put yourself through this, there's something called\rthe Internet.\r\rFirst Name:",
    'bbs_new_user_reg2_1':          'Es {}\rstill tu actual  BBS domestica? Y/N> ',
    'bbs_new_user_reg2_2':          'Usar esta BBS como TU BBS domestica? Y/N> ',
    'bbs_new_user_reg3':            'BBS domestica           :',
    'bbs_new_user_reg4':            '\rLo hiciste bien!\r\rDatos de usuario de $destCall:\rNombre: {}\rBBS domestica  : {}\rQTH       : {}\rLocator   : {}\r\r',
    'bbs_new_user_error_hbbs_add':  '\r # Error, el indicativo introducido no es una BBS.\r # {} Type is known as {}.\r # Por favor intentalo de nuevo.\r\r',
    'bbs_new_user_sysopMsg_top':    'Registro nuevo usuario',
    'bbs_new_user_sysopMsg_msg':    '{} acaba de ser conectado a {} por primera vez.\nTime: {}\n',
    'language':                     'Lenguaje',
    'temperature':                  'Temperatura',
    'wx_press':                     'Presión',
    'wx_hum':                       'Humedad',
    'userdb_add_sysop_ent1':        'Añadirninformación?',
    'userdb_add_sysop_ent2':        'Añadir informacion desde el sysop?',
    'userdb_save_hint':             'Info: Datos de usuario {} a sido salvado.',
    'userdb_del_hint1':             'borrar {}?',
    'userdb_del_hint2':             '{} seguro borrar?',
    'userdb_del_hint2_1':           'Borrar {} entradas?',
    'userdb_del_hint2_2':           'Seguro borrar todas  {} entradas?',
    'userdb_newUser':               'Nueva entrada',
    'prewritewin':                  'Ventana de preescritura',
    'consol_log':                   'Salida del Log en la consola',
    'call_vali_warning_1':          'Formato de Indicativo!',
    'call_vali_warning_2':          'Max 6 characteres solo letras mayusculas y  numeros.',
    'del_station_hint':             'Nota: Estacion borrada satisfactotiamente.',
    'del_station_warning_1':        'Estacion borrada',
    'del_station_warning_2':        'Unidad C: ha sido formateada satisfactoriamente.',
    'del_station_hint_1':           'borrar estación',
    'del_station_hint_2':           'Realmente quieres borrar esta estacion? \nAll configuración y textos se perderán!',
    'not_all_station_disco_hint_1': 'Estacion no desconecteda',
    'not_all_station_disco_hint_2': 'No todas las estaciones estan desconectadas!',
    'all_station_get_disco_hint_1': 'Estaciones siendo desconectadas!',
    'all_station_get_disco_hint_2': 'Todas las estaciones siendo desconectadas',
    'close_port':                   'Info: intenta cerrar puerto {}.',
    'port_closed':                  'Info: Puerto {} cerrado satisfactoriamente.',
    'send_kiss_parm':               'Nota: Parámetros Kiss enviados a la TNC en puerto {}..',
    'port_in_use':                  'Error: Puerto {} no puede ser inicializado. El puerto está  en uso.',
    'no_port_typ':                  'Nota: No hay  tipo de puerto seleccionado. puerto {}',
    'port_not_init':                'Error: Puerto {} no puede ser initializado.',
    'port_init':                    'Info: Puerto {} initializado satisfactoriamente.',
    'setting_saved':                'Info: {}-Parametros salvados.',
    'all_port_reinit':              'Info: Los puertos son reinicializados',
    'port_reinit':                  'Info: Puertos {} han sido reinitializados.',
    'all_disco1':                   'Todas las estaciones seran desconectadas!',
    'all_disco2':                   'Todas las estaciones han sido desconectadas',
    'OK':                           'OK',
    'cancel':                       'Cancelar',
    'aborted':                      'Abortado',
    'delete':                       'borrar',
    'next':                         'Siguiente',
    'back':                         'Atras',
    'delete_selected':              'Borrar selección',
    'add':                          'Añadir',
    'activate':                     'Activar',
    'delete_mh_history':            'Borrar Lista MH',
    'delete_dx_history':            'Borrar historial DX-Alarm',
    'delete_tracer_history':        'Borrar historial Trace',
    'delete_conn_history':          'Borrar historial de conexión',
    'del_all':                      'Borrar todo',
    'select_all':                   'Seleccionar todo',
    'go':                           'Ir',
    'close':                        'Cerrar',
    'save':                         'Salvar',
    'forward':                      'Adelante',
    'answer':                       'Rrspuesta',
    'send_file': 'Enviar fichero',
    'file_1': 'Fichero',
    'file_2': 'Fichero:',
    'locator_calc': 'Calculadora Locator',
    'aprs_mon': 'Monitor APRS',
    'protocol': 'Protocolo:',
    'distance': 'Distancia',
    'send_if_free': 'Enviar cuando la banda esté libre por (seg.): ',
    'size': 'Tamaño:',
    'new': 'Nuevo',
    'wait': 'Espere',
    'new_port': 'Nuevo puerto',
    'new_conn': 'Neva Conecxion',
    'disconnect': 'Desconectado',
    'disconnect_all': 'Desconnectar TODOS',
    'disconnect_all_ask': 'Quieres desconectar todas las estaciones?',
    'port_unblock_all': 'Permitir conexiones entrantes (todos los puertos)',
    'port_block_ignore_all': 'Ignorar confecciones entrantes  (todos los puertos)',
    'port_block_reject_all': 'Rechazar  conecxiones entrantes (todos los puertos)',
    'wx_window': 'Estaciones del tiempo',
    'quit': 'Quitar',
    'connections': 'Conecxiones',
    'copy': 'Copiar',
    'past': 'Pegar',
    'cut': 'Cortar',
    'past_f_file': 'Pegar desde Fichero',
    'save_to_file': 'Salvar a Fichero',
    'past_qso_f_file': 'Pegar desde Fichero',
    'save_qso_to_file': 'Salvar QSO a Fichero',
    'save_mon_to_file': 'Salvar Monitor a Fichero',
    'clean_prescription_win': 'Limpiar ventana de prescripción ',
    'clean_just_qso_win': 'Limpiar ventana de  QSO',
    'clean_qso_win': 'Limpiar ventana QSO/Prescripción',
    'clean_all_qso_win': 'Limpiar todas las ventanas de QSO/Prescripción',
    'send_selected': ' Enviar seleccionado',
    'clean_mon_win': 'Limpiar monitor',
    'edit': 'Editar',
    'statistic': 'Estadísticas',
    'history': 'Historia',
    'linkholder': 'titular de enlace',
    'right_level_editor': 'Editor de niveles de derechos',
    'clean_qso': 'borrar QSO',
    'tools': 'Herramientas',
    'station': 'Estacion',
    'stations': 'Estaciones',
    'port': 'Puerto',
    'address': 'Direccion',
    'channel': 'Canal',
    'beacon': 'Baliza',
    'sprech': 'Salida de voz',
    'settings': 'Ajustes',
    'main_page': 'Página principal',
    'password': 'Password',
    'passwords': 'Passwords',
    'syspassword': 'Sys-Password:',
    'trys': 'Intentos falsos:',
    'fillchars': 'Longitud de respuesta:',
    'priv': 'Login',
    'login_cmd': 'Comando de Login:',
    'command': 'Comando',
    'keybind': 'Distribución del teclado',
    'about': 'Acerca de',
    'help': 'Ayuda',
    'number': 'Numero',
    'seconds': 'Segubdo(s)',
    'minutes': 'Minuto(s)',
    'hours': 'Horas',
    'day': 'Día',
    'month': 'Mes',
    'occup': 'Ocupacion en %',
    'call': 'Llamada',
    'name': 'Nombre',
    'fwd_list': 'cola de avance',
    'fwd_path': 'Rutas de avance',
    'start_fwd': 'comienzo FWD',
    'start_auto_fwd': 'Comienzo de AutoFWD',
    'msg_center': 'Centro de Mensajes',
    'text_winPos': 'Posicion del texto (arriba/mitad/abajo)',
    'qso_win_color': 'Color de ventana de QSO',
    'text_color': 'Color de texto',
    'bg_color': 'Color de fondo',
    'backgrund': 'Fondo',
    'mon_color': 'Colores de Monitor',
    'c_text': 'Texto de conexión',
    'q_text': 'Texto Quitar',
    'i_text': 'Texto de Información',
    'li_text': 'Texto de Información larga',
    'news_text': 'Texto de Noticias',
    'comment': 'Comentario',
    'aprs_settings': 'Configuracion de APRS',
    'digi_settings': 'Configuracion DIGI',
    'aprs_server': 'Servidor APRS',
    'conn_2_aprs_server': 'Conectar a servidor APRS',
    'aprs_pn_msg': 'Mensajería APRS',
    'pn_msg': 'Mensajes Privados',
    'msg': 'Mensaje',
    'new_msg': 'Nuevo Mensaje',
    'aprs_digi_settings': 'Digipeater',
    'aprs_tracer_settings': 'Tracer',
    'digi_active': 'Activar APRS Digipeater',
    'digi_fillin': 'Fill-In Digipeater (solo WIDE1-1)',
    'digi_trace_active': 'Activar soporte TRACE',
    'digi_trace_all': 'TRACE también para WIDE2-n y superior',
    'digi_dup_time': 'Duplicar ventana de tiempo de filtro',
    'digi_ports': 'Digipeater activo en el siguiente puerto',
    'digi_hint': 'Nota:\n• Fill-In Digi solo digi-repite WIDE1-1 desde cualquier estación directa .\n• TRACE está destinado a uso experimental. Rutas / tracer .\n• El filtro duplicado previene bucles y repeticiones innecesarias.',
    'igate_settings': 'I-Gate',
    'igate_active': 'Activar I-Gate',
    'igate_rf_to_is': 'RF → APRS-IS (Subida)',
    'igate_is_to_rf': 'APRS-IS → RF (Bajada)',
    'igate_max_distance': 'Maxima distancia para  bajada',
    'igate_local_time': 'La estación es considerada local para',
    'igate_ports': 'Activo en Los siguientes puertos',
    'igate_dup_time': 'Ventana de filtro duplicado',
    'new_pr_mail': 'Nuevo PR-Mail',
    'send': 'Enviar',
    'save_draft': 'Salvar borrador',
    'save_draft_hint1': 'Borrador salvado!',
    'save_draft_hint2': 'El.mensaje ha sido salvado en el borrador.',
    'not_save_draft_hint1': 'Borrador no salvado!',
    'not_save_draft_hint2': 'El borrador no se puede salvar.',
    'del_message_hint1': 'Borrar mensaje?',
    'del_message_hint2': 'Realmente borrar mensaje?',
    'discard': 'Descartar',
    'invalid_call_warning1': 'Direccion incorrecta',
    'invalid_call_warning2': "La  dirección del destinatario es incorrecta. No BBS.",
    'invalid_axcall_warning1': 'Indicativo incorrecto',
    'invalid_axcall_warning2': 'El Indicativo que has introducido es incorrecto.',
    'send_all_now': 'Enviar todo ahora',
    'mark_all_read': 'Marcar como leído',
    'stat_settings': 'Estacion',
    'general_settings': 'General',
    'GPIO': 'GPIO',
    'gpio_fnc_setting_error_1': 'Sin funcion GPIO',
    'gpio_fnc_setting_error_2': 'Sin funcion GPIO asignada!',
    'Digipeater': 'Digipeater',
    'F-Text': 'F-Text',
    'MCast': 'MCast',
    'RX-Echo': 'RX-Echo',
    'new_stat': 'Nueva Estacion',
    'txt_decoding': 'Decodificacion de texto',
    'suc_save': 'Info: Configuración de estacion salvado.',
    'lob1': 'Elogio: Lo hiciste muy bien !!',
    'lob2': 'Elogio: Lo hiciste bien!!',
    'lob3': 'Elogio: Está fue una buena decisión. Sigue así. Lo hiciste bien.',
    'lob4': "Elogio: Hoy no te has ganado ningún elogio.",
    'lob5': "I'm sorry, Dave. I'm afraid I can't do that.",
    'hin1': 'Nota: El botón OK todavía funciona !!',
    'hin2': 'Nota: Cancelado !!',
    'date_time': 'Fecha/Hora',
    'time': 'Hora',
    'date': 'Fecha',
    'message': 'Mensaje',
    'titel': 'Título',
    'from': 'Desde',
    'to': 'Hacia',
    'subject': 'Sujeto',
    'versatz': 'Offset',
    'intervall': 'Intervalo',
    'active': 'Activado',
    'text_fm_file': 'Texto desde Fichero',
    'beacon_settings': 'Baliza',
    'pipetool_settings': 'Ajustes de Pipe-Tool',
    'new_pipe': 'Nuevo Pipe',
    'new_pipe_fm_connection': 'Pipe en Conecxion',
    'tx_file': 'TX Fichero',
    'rx_file': 'RX Fichero',
    'ax25_param': 'AX.25 parametros de conexión',
    'packet_timing_param': 'Paquete y parámetros de temporización',
    'backen_config': 'Configuración del backend',
    'net_ser_opt': 'Red / Opciones serie',
    'serial_interface': 'Interface Serie',
    'port_cfg_std_parm': 'Parametros por Defecto. Se utilizan si no están definidos en ningún otro lugar. (estacion/cliente).',
    'port_cfg_psd_txd': 'Retraso Pseudo TX (tiempo de espera entre TX y RX). No está configurado como un parametro KISS en la TNC.',
    'port_cfg_pac_len': 'Longitud de Paquete. 30-256',
    'port_cfg_pac_max': 'Paquetes Max. 1 - 7',
    'port_cfg_port_name': 'Designacion de puerto para MH y monitor (Max: 4):',
    'port_cfg_not_init': '!! El puerto no está inicializado!!',
    'new_beacon': 'Nueva Baliza',
    'last_packet': 'Ultimo paquete',
    'scrolling': 'Auto scrolling',
    'msg_box_mh_delete': 'Borrar lista MH',
    'msg_box_mh_delete_msg': 'Borrar la listaMH entera?',
    'msg_box_delete_data': 'Borrar datos',
    'msg_box_delete_data_msg': 'Borrar todos los mensajes?',
    'data': 'Datos',
    'multicast_warning': 'Tenga precaución con las conexiones de nodo como TNN. Linkando multiples nodos via multicast puede provocar problemas!',
    'connection_history': 'Historial de Conexión',
    'user_db': 'Base de datos Usuario',
    'show_in_userDB': 'Mostrar en DB-Usuario',
    'cmd_help_bell': 'Llamada a Sysop',
    'cmd_help_wx': 'Estaciones Meteorológicas',
    'cmd_help_user_db': 'Obtener entrada de BD de llamadas',
    'cmd_help_set_name': 'Introducir Nombre',
    'cmd_help_set_qth': 'Introducir QTH',
    'cmd_help_set_loc': 'Introducir Locator',
    'cmd_help_set_zip': 'Introducir Código Postal',
    'cmd_help_set_prmail': 'Introducir Dirección CORREO primario',
    'cmd_help_set_email': 'Introducir dirección E-MAIL',
    'cmd_help_set_http': 'Introducir HTTP',
    'cmd_help_aclear': 'Borrar / Limpiar mensajes APRS',
    'cli_error_no_call': ' # No hay call specifiecado.',
    'cli_error_no_call_in_mh_db': ' # {0} no encontrado en base de datos MH.',
    'cli_error': ' # Error.',
    'cli_no_user_db_ent': ' # Entrada no está enn base de datos usuario!',
    'cli_name_set': ' # Nombre de usuario es definido',
    'cli_qth_set': ' # QTH es definido',
    'cli_loc_set': ' # Locator es definido',
    'cli_zip_set': ' # Código Postal es definido',
    'cli_prmail_set': ' # Direccion PR-Correo es definida',
    'cli_email_set': ' # Dirección E-Mail es definida',
    'cli_http_set': ' # HTTP es definida',
    'cli_text_encoding_no_param': 'Ver/Cambiar la codificación de texto actual',
    'cli_text_encoding_error_not_found': " # No se pudo detectar la codificación de texto correcta.",
    'cli_text_encoding_set': ' # Decodificó texto se estableció en:',

    # New - Translated by Google
    'cli_text_encoding_current': 'Codificador utilizado actualmente',
    'cli_text_encoding_cmd_help': 'Establecer la codificación de texto con ENC <opt>',
    # END - Translated by Google

    'port_overview': 'Descripción general del puerto',
    'cmd_shelp': 'Ayuda abreviada',
    'time_connected': 'Duración de conexión',
    'cmd_not_known': 'El Sistema no Conoce este Comando !',
    'auto_text_encoding': 'Detección automática de la codificación de texto. ä como parámetro. > UM ä',
    'cmd_help_lcstatus': 'Muestra canales de terminal conectados (version detallada)',
    'cmd_help_cstat': 'Estadisticas de Conecxión de los Ultimos 7 días',
    'cmd_help_chist': 'Historial de  Conexión (últimos 30 días)',
    'cmd_help_ch': 'Enviar mensaje corto a canal. CH <Channel> Mensaje',
    'cmd_help_rtt': 'Medición del tiempo de ejecución de paquetes',
    'cmd_help_bwstat': 'Band Utilización de Banda últimos 10 minutos',
    'cli_no_wx_data': 'No hay datos WX disponibles',
    'cli_no_data': 'No hay datos disponibles.',
    'cli_no_tracer_data': 'No hay datos Tracerdisponibles ',
    'cli_change_language': 'Cambiar lenguaje.',
    'cli_lang_set': 'Lenguaje cambiado a Ingles.',
    'cli_no_lang_param': 'Lenguaje no reconocido! Posibles lenguajes: ',
    'cmd_rtt_1': ' # Tiempo de viaje de ida y vuelta: ',
    'cmd_bell': 'Llamada al Sysop!!',
    'cmd_bell_again': 'El Sysop ha sido otra vez llamado..',
    'cmd_bell_gui_msg': 'pregunte por el sysop!!',
    'cmd_c_noCall': '# Por favor introduzca llamada..',
    'cmd_c_badCall': '# Destino de Llamada Invalido..',
    'cmd_c_badPort': '# Invalida Especificación de puerto..',
    'cmd_c_noPort': '# Puerto invalido..',
    'ch_cmd_param_error': '#  Parámetros invalidos . Mensaje CH <Channel> ',
    'ch_cmd_empty_ch': '# Canal invalido. Canal no conectado.',
    'ch_cmd_own_ch': '# No se puede enviar mensaje a tu propio canal .',
    'ch_cmd_send': '# Memsaje a canal {} ({}).\r',
    'cmd_bwstat_1': 'Total ancho de banda utilizado (últimos 10 minutos, todos los puertos)',
    'cmd_bwstat_2': 'Utilización de banda en todos los puertos(%) – Tendencia de 10 minutos',
    'cmd_bwstat_3': 'Utilización de banda en puerto {} (%) – Tendencia de 10 minutos',
    'last_30_days': 'últimos 30 días',
    'cmd_chist_tab': 'Fecha       Hora     Dur.    Call      Puerto  Locator / Distancia\r',
    'cmd_help_mcast_move_ch': 'Cambiar canal MCast',
    'cmd_help_mcast_ch_info': 'Info de canal MCast',
    'cmd_help_mcast_channels': 'descripción general del canal MCast',
    'cmd_help_mcast_set_axip': 'Introduce/muestra tu propia dirección AXIP',
    'mcast_new_user_beacon': '-= Bienvenido al AXIP-MCast Server. Por favor conecte {} para registrar =-',
    'mcast_new_user_reg_beacon': '-= As sido satisfactoriamente registrado en el MCast server =-\r-= Tu estás en el canal {} ({}) =-',
    'mcast_user_enters_channel_beacon': '-= {} ha entrado al canal =-',
    'mcast_user_left_channel_beacon': '-= {}  ha abandonado el canal=-',
    'hint_no_mail_for': '\r # No hay correos disponibles: {}',
    'hint_no_mail': '\r # No hay correos disponibles',
    'cmd_fwdinfo': 'Muestra estadísticas hacia adelante',
    'cmd_r': '<MSG#>: Lee el mensaje con el número correspondiente..',
    'cmd_sp': 'SP <Call> @ <BBS>: Envía un mensaje  personal al indicativo',
    'cmd_sb': 'SB <Category> @ <Distribution>: Envia un boletín a la categoría \r              para varias cajas en una región.',
    'cmd_sr': 'SR <Msg#> : Envía una respuesta a la remitente(\r              of <Msg#> = mensaje numero (Envia Respuesta).',
    'cmd_ln': 'Muestra todos tus mensajes nuevos.',
    'cmd_lm': 'Enumera todos tus propios mensajes.',
    'cmd_ll': '<Number>: Enumera las últimas noticias en el número especificado.',
    'cmd_l_from': '<CALL>: Lista boletines DE un indicativo de llamada.',
    'cmd_l_to': '<CALL/RUBRIK>: Lista mensajes A de un Indicativo de llamada o dirección.',
    'cmd_l_at': '<CALL>: Listados de boletines VIA distribución.',
    'cmd_lb': 'Muestra todos los mensajes del boletín.',
    'cmd_km': 'Elimina todos los mensajes personales que ya has leído.',
    'cmd_k': '<MSG#>: Elimina el mensaje con el número correspondiente.',
    'cmd_mr': 'Marca todos los mensajes personales como leídos.',
    'box_cmd_mr_msg': '\r # {} mensaje(s) fueron marcados como leídos.\r',
    'cmd_op': 'Número de líneas por página. Sólo OP = off.',
    'op_prompt_0': '\r # (A)=Cancelar, (O)=continuar sin parar, (Return)=continuar -->',
    'op_prompt_1': '\r # (A)=Cancelar, (R)=Leer, (Return)=continuar -->',
    'aprs_new_mail_ctext': '\r # APRS: Tu tienes {} nuevos mensaje(s). Lectura con AMS\r',
    'box_new_mail_ctext': '\r # BOX: Ud tiene {} nuevos mails.\r',
    'box_no_hbbs_address': "\r # Todavía no has entrado en un BBS privado. PR <CALL.Distribution>\r",
    'box_cmd_op2': '\r # OP : Error, Parametro Invalido.\r',
    'box_cmd_op1': '\r # OP : Sin parada lateral.\r',
    'box_cmd_op3': '\r # OP : Parada de página establecida en {} líneas.\r',
    'box_lm_header': 'Msg#  TSLD Byte   Para    @ BBS   De   Fech./Hora Título\r',
    'box_r_no_msg_found': '\r\r # Mensaje {} no encontrado! \r\r',
    'box_parameter_error': '\r # Error,  Parametro Inválido.\r',
    'box_msg_error': '\r # Error Interno, no puedo leer el mensaje.\r',
    'box_msg_foter': '\r\r--- Fin del mensaje #{} para {} de {} BID:{} ---\r\r',
    'box_msg_del': '\r # {} los mensajes han sido eliminados.\r',
    'box_msg_del_k': '\r # MESSAGE(s) {} han sido eliminados.\r',
    'box_error_no_address': '\r # No se ha especificado ningún destinatario. SP XX0XX o SP XX0XX@XBBS0.\r',
    'box_error_invalid_dist': '\r # No hay lista de distribución en la dirección BBS {}\r',
    'box_cmd_sp_routing_to': '\r # Enrutamiento: {}\rTítulo del mensaje para {}:\r',
    'box_cmd_sp_local': '\r # Mensaje local .\rTítulo del mensaje para {}:\r',
    'box_cmd_sr_enter_msg': 'La respuesta va a {}\r',
    'box_cmd_sp_enter_msg': 'Introducir texto ... (Termina con /EX o Ctrl-Z):\r',
    'box_cmd_sp_abort_msg': '\r # Mensaje para {} cancelado\r\r',
    'box_cmd_sp_msg_accepted': '\r # Ok. Mensaje a la dirección {} @ {} está siendo reenviado\r   via: {} Mid: {} Bytes: {}\r\r',
    'box_cmd_sp_msg_accepted_local': '\r # Ok. Mensaje a la dirección {} restando local.\r   MID: {} Bytes: {}\r\r',
    'own_station': 'Estación propia',
    'region': 'Region',
    'fwd_settings': 'Adelante',
    'fwd_port_settings': 'FWD-Puerto',
    'routing_settings': 'Enrutamiento',
    'reject_settings': 'Rechazar/Retener',
    'cc_settings': 'CC',
    'AutoMail_settings': 'Correos automáticos',
    'swap_settings': 'INTERCAMBIO',
    'noConnect': 'No hay conexión saliente',
    'allowPN_AutoPath': 'Permitir Ruta automática PN',
    'allowPN_AlterPath': 'Permitir ruta alternativa PN',
    'allow_PN_FWD': 'Permitir correo privado FWD',
    'allow_BL_FWD': 'Permitir Boletín de correo FWD',
    'conn_intervall': 'Intervalos entre conexiones (minutos): ',
    'conn_timeout': 'Se acabó el tiempo (minutos): ',
    'fwd_autoPath_help': '0 = disactivado\n1 = más reciente\n2 = mejor (Ruta más corta)',
    'bbs_sett_fwd_global': 'Reenvío global',
    'bbs_sett_local_dist': 'Distribuidores locales',
    'bbs_sett_local_theme': 'Temas del boletín local',
    'bbs_sett_block_bbs': 'Bloquear BBS',
    'bbs_sett_block_call': 'Bloquesr CALL',
    'bbs_sett_pn_bbs_out': 'Mail privado > saliente',
    'bbs_sett_pn_bbs_in': 'Mail privado > saliente',
    'bbs_sett_bl_bbs_in': 'Correo de boletín > saliente',
    'bbs_sett_bl_bbs_out': 'Correo de boletín > saliente',
    'read_ed': 'leer',
    'msgC_sendet_msg': 'Enviado',
    'msgC_trash_bin': 'Papelera',
    'saved': 'Salvado',
    'private': 'Privado',
    'key_title': 'Distribución del teclado',
    'key_esc': 'ESC > Nueva conecxión',
    'key_altc': 'ALT + C > Nueva conecxión',
    'key_altd': 'ALT + D > Desconectado',
    'key_f': 'F1 - F10 > Canal 1 - 10',
    'key_f12': 'F12 > Monitor',
    'key_strgplus': 'CTRL + más > Aumenta tamaño texto',
    'key_strgminus': 'CTRL + menos > Reduce tamaño texto',
    'key_shiftf': 'SHIFT + F1 - F12 > Macros de texto',
    'newcon_title': 'Nueva Conecxión',
    'ziel': 'Destino',
    'newcon_history': 'Historial',
    'scheduler': 'Programador',
    'type': 'Tipo:',
    'week_day': 'Días de la semana',
    'month_day': 'Días del mes',
    'intervall_mn': 'Intervalo (mn): ',
    'offset_sec': 'Offset (sec): ',
    'reset': 'Reset',
    'scheduler_set': 'Ajuste de Programador',
    'echo_warning': 'Atención! Esta función no reemplaza al digipeater!',
    'mon_start_msg1': 'Info: Dato de estation {} cargado sutisfactoriamente.',
    'mon_start_msg2': 'no puede ser inicializado!',
    'mon_start_msg3': 'inicializado satisfactoriamente.',
    'mon_end_msg1': 'Saliendo de PoPT.',
    'ENDE':                         'FIN',
    'FREI':                         'LIBRE',
    'AUFBAU':                       'INICIALIZADO',
    'ABBAU':                        'DESCONECTADO',
    'BEREIT':                       'LISTO',
    'Abgebrochen':                  'Discontinuado',
    'Abgebrochen_msg':              'Fue una muy buena decisión. \nLo hiciste bien, sigue así.',
    'Port_gelöscht':                'Puerto borrado',
    'Port_gelöscht_msg':            'La Internet ha sido eliminado con éxito.',
    'losche_Port':                  'borrar puerto',
    'losche_Port_msg':              'Estás seguro de que quieres eliminar este puerto? \nAll la configuración se perderá!',
    'invalid_call_titel':           'Indicativo Invalido',
    'invalid_call_msg':             'La llamada al administrador del sistema introducida no es válida.',
    'wizard_done':                  'La configuración  de PoPT está  ahora completa.',
    'wizard_want_port_setup':       'Quieres configurar un puerto AX25 ?',
    'yes':                          'Si',
    'no':                           'No',
    'right_level_editor_title':     'Editor de Niveles de Permiso',
    'glb_rights_txt':               'Permisos PRP globales (glb_rights)',
    'new_user_std_level':           'Nivel por defecto para nuevos usarios:',
    'allow_remote_access':          'Generalmente se permite el acceso remoto',
    'allow_login':                  'Permitir permisos extendidos solo después de iniciar sesión',
    'edit_rights':                  'Administrar niveles de derechos',
    'new_level':                    'Añadir Nuevo Nivel',
    'rename_level':                 'Renombrar Nivel',
    'delete_level':                 'Borrar nivel',
    'with_login':                   'Con Logeo',
    'without_login':                'Sin Logeo',
    'new_level_name':               'Nombre del nuevo nivel de derechos:',
    'already_exists':               'Ya Existe',
    'level_name_already_exists':    "El nivel '{}' ya existe!",
    'error_delete_standard_level':  'El nivel predeterminado actual no se puede eliminar!',
    'ask_delete_level':             "Realmente eliminar los derechos de nivel '{}'?",
    'new_name':                     'Nuevo Nombre',
    'error':                        'Error',
    'remote_rights':                'Derechos remotos',
    'right_level':                  'Nivel de derechos',
    'block_remote_access':          'Prohibir completamente el acceso remoto (bloqueado)',
    'individual_rights':            'Derechos Individuales',
    'password_for_prp_login':       'Contraseña de acceso (para logeo PRP)',
    'show':                         'Mostrar',
    'aprs_chat_invalid_target':     ' # Llamada Invalida o destino (TODO/CQ)',
    'aprs_chat_no_service':         ' # APRS-SMS servico no disponible.',
    'aprs_chat_exit':               ' # APRS Chat finalizado.',
    'aprs_chat_title':              '=== APRS Chat con {0} en Puerto {1} via {2} ===',
    'aprs_chat_enter':              'Introduce mensajes directamente. //EXIT para salir.',
    'aprs_chat_help':               'Ayuda con //H or //HELP',
    'aprs_msgs_title':              '=== APRS Mensakes ===',
    'aprs_msgs_more':               '... y mas mensajes',
    'aprs_recent_title':            '--- Últimos Mensajes APRS ({0}) ---',
    'aprs_recent_no_unread':        ' # Mensajes APRS no leídos para {0}.',
    'aprs_recent_all_cmd':          'Todos los mensajes con //AMSGS',
    'aprs_clear_done':              ' # lista de mensajes APRS limpida.',
    'aprs_chat_help_title':         '=== Ayuda Chat APRS ===',
    'aprs_chat_help_border':        '--------------------------------------------------',
    'aprs_chat_help_h':             '  //H  or  //HELP      - Esta ayuda',
    'aprs_chat_help_exit':          '  //EXIT or  //Q       - Dejar el chat',
    'aprs_chat_help_max_hops':      '  //WIDE <HOPS>        - Definir maximos saltos (1-7) (WIDE[x]-[x])',
    'aprs_chat_help_amsgs':         '  //AMSGS [n]          - Mostrar todos los mensajes',
    'aprs_chat_help_aclear':        '  //ACLEAR             - Borrar / Limpiar Mensajes APRS',
    'aprs_chat_help_achange':       'Cambiar objetivo (sin dejar ell chat):',
    'aprs_chat_help_achat':         '  //ACHAT <Call> [Puerto]  - Chat con la estación',
    'aprs_send_error':              ' # Error enviando mensaje APRS.',
    # By Google Translater
    'default_text':                 'Texto predeterminado',

    # ===== POKER =====================================================
    'poker_title':                  '\r=== Texas Hold\'em Poker ===\r',
    'poker_table_header':           'Tu: {0:>4} Chips   Dealer: {1:>4}   Pote: {2:>4}\r\r',
    'poker_your_cards':             'Tus Cartas:   ',
    'poker_dealer':                 'Dealer:        ',
    'poker_community':              'Comunidad:     ',
    'poker_your_hand':              'Tu Mano:       ',
    'poker_prompt':                 '\rBET <cant> | CHECK | CALL | FOLD\r',
    'poker_cant_check':             '\r # No puedes CHECKear, el dealer apostó. CALL o FOLD.\r',
    'poker_invalid_bet':            '\r # Cantidad no válida!\r',
    'poker_quit':                   '\r # Poker terminado.\r',
    'poker_unknown_cmd':            '\r # Comando desconocido. BET <cant> | CHECK | CALL | FOLD\r',
    'poker_player_folded':          'Te has retirado.',
    'poker_dealer_wins_pot':        'Dealer gana {:d} fichas.',
    'poker_new_round':              '\rNueva ronda con //POKER\r',
    'poker_no_chips_new_game':      '\rNo quedan fichas! Nuevo juego con //POKER\r',
    'poker_must_call':              '\r # Debes al menos CALLear (apuesta actual: {}) o FOLDear.\r',
    'poker_both_check':             'Ambos checkean.',
    'poker_dealer_folds':           'Dealer se retira.',
    'poker_dealer_raised':          'Dealer subió {}.',
    'poker_dealer_raises_to':       'Dealer sube a {}. Tu apuesta: {}',
    'poker_dealer_called':          'Dealer pagó ({}).',
    'poker_player_calls':           'Pagas.',
    'poker_dealer_bets':            'Dealer apuesta {}.',
    'poker_dealer_bets_line':       'Dealer apuesta {} fichas.',
    'poker_player_hand_label':      'Tú ({}): {}',
    'poker_dealer_hand_label':      'Dealer ({}): {}',
    'poker_win':                    '★★★ GANASTE! ★★★   +{} fichas',
    'poker_tie':                    'Empate! Pote dividido. +{} fichas',
    'poker_dealer_wins_showdown':   'Dealer gana con {}.',
    'poker_your_balance':           'Tu saldo: {} fichas',
    'poker_no_chips':               '\r # No te quedan fichas! Juego terminado.\r\rInicia un nuevo juego con //POKER\r',
    'poker_game_over':              '\rJuego terminado! Nuevo juego con //POKER\r',
    'poker_help':                   ('\r'
                                     '=== Texas Hold\'em Poker ===\r'
                                     'Comandos:\r'
                                     '  //POKER          Nuevo juego\r'
                                     '  //POKER HANDS    Mostrar ranking de manos\r'
                                     '  //POKER HIGH     Highscore\r'
                                     '\r'
                                     'En juego:\r'
                                     '  BET <cant>  Apostar\r'
                                     '  CHECK       Pasar (solo si no hay apuestas abiertas)\r'
                                     '  CALL        Igualar apuesta del dealer\r'
                                     '  RAISE <cant> Subir\r'
                                     '  FOLD        Retirarse\r'
                                     '  QUIT        Terminar juego\r'),
    'poker_hand_ranking_title':     ('\rRanking de Manos de Poker (descendente):\r'
                                     '  9  Royal Flush\r'
                                     '  8  Straight Flush\r'
                                     '  7  Four of a Kind\r'
                                     '  6  Full House\r'
                                     '  5  Flush\r'
                                     '  4  Straight\r'
                                     '  3  Three of a Kind\r'
                                     '  2  Two Pair\r'
                                     '  1  One Pair\r'
                                     '  0  High Card\r'),
    'poker_highscore_not_impl':     '\r # Highscore aún no implementado.\r',
}



