STR_TABLE = {
    #  GER   ENG
    'OK': ('OK', 'OK'),
    'cancel': ('Abbrechen', 'Cancel'),
    'delete': ('Löschen', 'Delete'),
    'save': ('Speichern', 'Save'),
    'send_file': ('Datei senden', 'Send File'),
    'file_1': ('Datei', 'File'),
    'file_2': ('Datei:', 'File:'),
    'protocol': ('Protokoll:', 'Protocol:'),
    'send_if_free': ('Senden wenn Band frei für (sek.):', 'Send when band is free for (sec.):'),
    'size': ('Größe:', 'Size:'),
    'new': ('Neu', 'New'),
    'disconnect': ('Disconnect', 'Disconnect'),
    'quit': ('Quit', 'Quit'),
    'connections': ('Verbindungen', 'Connections'),
    'copy': ('Kopieren', 'Copy'),
    'past': ('Einfügen', 'Past'),
    'past_f_file': ('Aus Datei einfügen', 'Past from File'),
    'save_to_file': ('QSO in Datei speichern', 'Save QSO to File'),
    'save_mon_to_file': ('Monitor in Datei speichern', 'Save Monitor to File'),
    'clean_qso_win': ('QSO/Vorschreibfenster löschen', 'Clear QSO/Prescription window'),
    'clean_mon_win': ('Monitor löschen', 'Clear Monitor'),
    'edit': ('Bearbeiten', 'Edit'),
    'statistic': ('Statistik', 'Statistics'),
    'linkholder': ('Linkhalter', 'Link holder'),
    'tools': ('Tools', 'Tools'),
    'station': ('Station', 'Station'),
    'port': ('Port', 'Port'),
    'channel': ('Kanal', 'Channel'),
    'beacon': ('Baken', 'Beacons'),
    'settings': ('Einstellungen', 'Settings'),
    'keybind': ('Tastaturbelegung', 'Keyboard layout'),
    'about': ('Über', 'About'),
    'help': ('Hilfe', 'Help'),
    'minutes': ('Minuten', 'Minutes'),
    'hours': ('Stunden', 'Hours'),
    'day': ('Tag', 'Day'),
    'month': ('Monat', 'Month'),
    'occup': ('Auslastung in %', 'Occupancy in %'),
    'call': ('Call', 'Call'),
    'name': ('Name', 'Name'),
    'c_text': ('C Text', 'C Text'),
    'q_text': ('Quit Text', 'Quit Text'),
    'i_text': ('Info Text', 'Info Text'),
    'li_text': ('Lang-Info Text', 'Long-Info Text'),
    'news_text': ('News Text', 'News Text'),
    'stat_settings': ('Station-Einstellungen', 'Station-Settings'),
    'new_stat': ('Neue Station', 'New Station'),
    'suc_save': ('Info: Station Einstellungen erfolgreich gespeichert.', 'Info: Station settings saved successfully.'),
    'lob1': ('Lob: Das hast du sehr gut gemacht !!', 'Praise: You did very well!!'),
    'lob2': ('Lob: Das hast du gut gemacht !!', 'Praise: You did well!!'),
    'hin1': ('Hinweis: Der OK Button funktioniert noch !!', 'Note: The OK button still works !!'),
    'from': ('Von', 'From'),
    'to': ('An', 'To'),
    'versatz': ('Versatz', 'Offset'),
    'intervall': ('Intervall', 'Interval'),
    'active': ('Aktiviert', 'Activated'),
    'text_fm_file': ('Text aus Datei', 'Text from File'),
    'beacon_settings': ('Baken-Einstellungen', 'Beacon-Settings'),
    'pipetool_settings': ('Pipe-Tool Einstellungen', 'Pipe-Tool Settings'),
    'new_pipe': ('Neue Pipe', 'New Pipe'),
    'tx_file': ('TX Datei', 'TX File'),
    'rx_file': ('RX Datei', 'RX File'),
    'new_beacon': ('Neue Bake', 'New Beacon'),
    'last_packet': ('letztes Paket', 'Last Seen'),
    'scrolling': ('Auto Scrollen', 'Auto scrolling'),
    'multicast_warning': ('Vorsicht bei Nodenanbindungen wie TNN. Verlinkungen mehrerer Noden via Multicast kann zu Problemen führen!', 'Be careful with node connections like TNN. Linking multiple nodes via multicast can lead to problems!'),

}
