SQL_CREATE_BBS_PN_MAIL_TAB = ("CREATE TABLE bbs_pn_msg (\n"
                              "	BID varchar(100) NOT NULL,\n"
                              "	`from_call` VARCHAR(100) NOT NULL,\n"
                              "	`from_bbs` VARCHAR(100) NULL,\n"
                              "	`to_call` varchar(100) NOT NULL,\n"
                              "	`to_bbs` varchar(100) NULL,\n"
                              "	`size` BIGINT UNSIGNED NULL,\n"
                              "	`subject` varchar(100) NULL,\n"
                              "	`header` BLOB,\n"
                              "	`msg` LONGBLOB,\n"
                              "	`path` VARCHAR(2048) NULL,\n"
                              "	time varchar(100) NULL,\n"
                              "	PRIMARY KEY (BID)\n"
                              ");\n")
SQL_CREATE_BBS_BL_MAIL_TAB = ("CREATE TABLE bbs_bl_msg (\n"
                              "	BID varchar(100) NOT NULL,\n"
                              "	`from_call` VARCHAR(100) NOT NULL,\n"
                              "	`from_bbs` VARCHAR(100) NULL,\n"
                              "	`to_call` varchar(100) NOT NULL,\n"
                              "	`to_bbs` varchar(100) NULL,\n"
                              "	`size` BIGINT UNSIGNED NULL,\n"
                              "	`subject` varchar(100) NULL,\n"
                              "	`header` BLOB,\n"
                              "	`msg` LONGBLOB,\n"
                              "	`path` VARCHAR(2048) NULL,\n"
                              "	time varchar(100) NULL,\n"
                              "	PRIMARY KEY (BID)\n"
                              ");\n")
