SQL_CREATE_BBS_OUT_MAIL_TAB = ("CREATE TABLE bbs_out_msg (\n"
                               "`MID` INT(6) AUTO_INCREMENT NOT NULL,\n"
                               "`BID` varchar(12),\n"
                               "`from_call` VARCHAR(10) NOT NULL,\n"
                               "`from_bbs` VARCHAR(40) NULL,\n"
                               "`from_bbs_call` VARCHAR(100) NULL,\n"
                               "`to_call` varchar(10) NOT NULL,\n"
                               "`to_bbs` varchar(40) NULL,\n"
                               "`to_bbs_call` varchar(10) NULL,\n"
                               "`size` BIGINT UNSIGNED NULL,\n"
                               "`subject` varchar(100) NULL,\n"
                               "`header` BLOB,\n"
                               "`msg` LONGBLOB,\n"
                               # "`sent_to` VARCHAR(202) DEFAULT '[]' NULL,\n"
                               "`time` varchar(30) NULL,\n"
                               "`utctime` varchar(30) NULL,\n"
                               "`type` varchar(1) NOT NULL,\n"
                               "`flag` varchar(2) DEFAULT 'E' ,\n"
                               "PRIMARY KEY (MID)\n"
                               ");\n")

SQLITE_CREATE_BBS_OUT_MAIL_TAB = ("CREATE TABLE bbs_out_msg (\n"
                                  "`MID` INTEGER PRIMARY KEY AUTOINCREMENT,\n"
                                  "`BID` varchar(12),\n"
                                  "`from_call` VARCHAR(10) NOT NULL,\n"
                                  "`from_bbs` VARCHAR(40) NULL,\n"
                                  "`from_bbs_call` VARCHAR(100) NULL,\n"
                                  "`to_call` varchar(10) NOT NULL,\n"
                                  "`to_bbs` varchar(40) NULL,\n"
                                  "`to_bbs_call` varchar(10) NULL,\n"
                                  "`size` BIGINT UNSIGNED NULL,\n"
                                  "`subject` varchar(100) NULL,\n"
                                  "`header` BLOB,\n"
                                  "`msg` LONGBLOB,\n"
                                  # "`sent_to` VARCHAR(202) DEFAULT '[]' NULL,\n"
                                  "`time` varchar(30) NULL,\n"
                                  "`utctime` varchar(30) NULL,\n"
                                  "`type` varchar(1) NOT NULL,\n"
                                  "`flag` varchar(2) DEFAULT 'E'\n"
                                  ");\n")

SQL_CREATE_BBS_FWD_TASK_TAB = ("CREATE TABLE bbs_fwd_q (\n"
                               "`FWDID` varchar(20) NOT NULL,\n"
                               "`BID` varchar(12) NOT NULL,\n"
                               "`MID` INT NOT NULL,\n"
                               "`from_call` varchar(10) NOT NULL,"
                               "`from_bbs` varchar(40) NOT NULL,"
                               "`from_bbs_call` varchar(10) NOT NULL,"
                               "`to_call` varchar(10) NOT NULL,"
                               "`to_bbs` varchar(40) NOT NULL,"
                               "`to_bbs_call` varchar(10) NOT NULL,"
                               "`fwd_bbs_call` varchar(10) NOT NULL,"
                               "`size` BIGINT UNSIGNED NULL,\n"
                               "`type` varchar(1) NOT NULL,\n"
                               "`flag` varchar(2) DEFAULT 'F' NOT NULL,\n"
                               "`try` TINYINT DEFAULT 0,\n"
                               "`tx_time` varchar(30) NULL,\n"
                               "PRIMARY KEY (FWDID)\n"
                               ");\n"
                               )

SQL_CREATE_BBS_PN_MAIL_TAB = ("CREATE TABLE bbs_pn_msg (\n"
                              "	`BID` varchar(20) NOT NULL,\n"
                              "	`from_call` VARCHAR(100) NOT NULL,\n"
                              "	`from_bbs` VARCHAR(100) NULL,\n"
                              "	`to_call` varchar(100) NOT NULL,\n"
                              "	`to_bbs` varchar(100) NULL,\n"
                              "	`size` BIGINT UNSIGNED NULL,\n"
                              "	`subject` varchar(100) NULL,\n"
                              "	`header` BLOB,\n"
                              "	`msg` LONGBLOB,\n"
                              "	`path` VARCHAR(2048) NULL,\n"
                              "	`time` varchar(30) NULL,\n"
                              "	`new` TINYINT(1) DEFAULT 1 NOT NULL,\n"
                              "	PRIMARY KEY (BID)\n"
                              ");\n")
SQL_CREATE_BBS_BL_MAIL_TAB = ("CREATE TABLE bbs_bl_msg (\n"
                              "	`BID` varchar(20) NOT NULL,\n"
                              "	`from_call` VARCHAR(100) NOT NULL,\n"
                              "	`from_bbs` VARCHAR(100) NULL,\n"
                              "	`to_call` varchar(100) NOT NULL,\n"
                              "	`to_bbs` varchar(100) NULL,\n"
                              "	`size` BIGINT UNSIGNED NULL,\n"
                              "	`subject` varchar(100) NULL,\n"
                              "	`header` BLOB,\n"
                              "	`msg` LONGBLOB,\n"
                              "	`path` VARCHAR(2048) NULL,\n"
                              "	`time` varchar(30) NULL,\n"
                              "	PRIMARY KEY (BID)\n"
                              ");\n")

SQL_CREATE_FWD_PATHS_TAB = ("CREATE TABLE fwdPaths (\n"
                            "`path` varchar(300) NOT NULL,\n"
                            "destBBS varchar(30) NOT NULL,\n"
                            "fromBBS varchar(30) NOT NULL,\n"
                            "hops TINYINT DEFAULT 0 NOT NULL,\n"
                            "destR1 varchar(10) NULL,\n"
                            "destR2 varchar(10) NULL,\n"
                            "destR3 varchar(10) NULL,\n"
                            "destR4 varchar(10) NULL,\n"
                            "destR5 varchar(10) NULL,\n"
                            "destR6 varchar(10) NULL,\n"
                            "lastUpdate varchar(30) NOT NULL,\n"
                            "PRIMARY KEY (`path`)\n"
                            ");\n")

SQL_GET_LAST_MSG_ID = "SELECT MID FROM bbs_out_msg ORDER BY MID DESC LIMIT 1;"
SQL_BBS_OUT_MAIL_TAB_IS_EMPTY = "SELECT CASE WHEN EXISTS(SELECT 1 FROM bbs_out_msg) THEN 0 ELSE 1 END AS IsEmpty;"

